### ISSUE TITLE
Monitor system idle time for natural breaks

### ISSUE THREAD

**Issue by mdekstrand** [hovancik/stretchly#59] opened 2017-02-10 20:18 UTC
It'd be fantastic if stretchly could monitor user idle time for 'natural' breaks - if I've been away for the computer for 10 minutes, for example, it should count as my last break and restart the timer when I come back. Ditto for 1-minute rests resetting the microbreak timer.

Both Workrave and Time Out (for Mac) have this feature.

I do not know if Electron exposes the necessary hooks to implement it. It may require platform-specific binary extensions, unfortunately.

**Comment by hovancik** [comment] 2017-02-11 13:10
I've been looking into that some time ago, there was some node package. Not sure how platform specific.

**Comment by chuck13** [comment] 2017-02-13 02:24
I found this module (https://github.com/paulcbetts/node-system-idle-time) while trying to add idle detect support, It seemed enough for me.

p.s. another way to add idle detection on OS X http://stackoverflow.com/questions/2922846/detecting-user-activity-on-mac-os-x

**Comment by hovancik** [comment] 2017-02-13 09:00
that package is for linux only, right? @chuck13

**Comment by chuck13** [comment] 2017-02-13 09:41
@hovancik no, it's for Linux, OS X and Windows 😃

**Comment by hovancik** [comment] 2017-02-13 09:44
Ah, I see. I misread the readme ;]

**Comment by birkany** [comment] 2017-03-19 04:06
But what if I was reading a technical article and looking to an equation for more than 10 minutes? It is not an idle time actually. It may be hard to distinguish this natural breaks. So I may suggest adding a reading mode also, so the application won't try to detect natural breaks and continue counting down when the reading mode is selected. Some users may like to use in reading mode always, if their work is reading intensive.

**Comment by mdekstrand** [comment] 2017-03-20 02:01
@birkany having it configurable would make sense, particularly since different people have different needs.

I use it almost entirely to manage RSI, with vision breaks as a side benefit, so as long as I am not operating the keyboard or mouse, I am 'taking a break'.

**Comment by hovancik** [comment] 2017-03-20 10:21
Hey guys, 

just wanted to let you know, that this feature is coming very slow (in fact, I am not working at it now). In those mentioned npm packages, there is stuff I do not understand, so I am a bit like "not wanna use them" right now. 

Anyhow, I am thinking about adding it for macOS as test. How about showing notification, when idle time is detected?

**Comment by chuck13** [comment] 2017-03-20 12:33
That would be very cool, I'm looking forward to the new feature.

**Comment by mdekstrand** [comment] 2017-05-06 16:21
I have started working on this in a branch on my fork, but am currently running in to a problem where the Electron process cannot load the system-idle-time bindings.

**Comment by hovancik** [comment] 2017-05-06 19:19
@mdekstrand how about going with macOS only right now? 

with `ioreg -c IOHIDSystem | awk '/HIDIdleTime/ {print $NF/1000000000; exit}'`

**Comment by hovancik** [comment] 2017-05-06 19:34
Anyway, we should maybe use https://github.com/electron-userland/electron-forge which should take care of the problem with native modules, but it's big change.

**Comment by mdekstrand** [comment] 2017-05-06 21:49
@hovancik Windows is my only desktop platform right now.

Does the `BreaksPlanner` code get run in the Chrome front-end process or the Node back-end? That is where I am trying to load the system-ide-time module.

**Comment by mdekstrand** [comment] 2017-05-06 22:07
Turns out that `electron-rebuild` will fix the problem. https://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by hovancik** [comment] 2017-08-29 13:32
PR was updated with master, would need help with understanding how it works.

**Comment by hovancik** [comment] 2017-09-30 13:10
New PR her: https://github.com/hovancik/stretchly/pull/140

**Comment by decadent** [comment] 2017-10-16 02:58
(Posting this here so it's preserved outside of the PR.)

So far with #140 on OSX it seems that the detection pretty much doesn't work at all. I have a time tracker installed, and Stretchly begins a new break at random time marks after a natural break. Also sometimes I wake the machine from the screensaver to be greeted with an open microbreak window.

From the experience with other break reminders and time trackers, idle time detection is apparently a not-so-simple task on OSX. Time Out has two methods for detection, one of which requires granting the permission to access the Accessibility API:

![Time Out idle detection options](https://i.imgur.com/yWDdR84.png)

I must note that 'Event Source' works well enough. The names of the options suggest that the app receives some events from the system for idle periods start/end, but I don't know what the APIs are, and unfortunately Time Out is not open source. Possibly this involves Cocoa events aka 'notifications.'

[The desktop client for Toggl](https://github.com/toggl/toggldesktop) detects idle time pretty well without access to the Accessibility API, and it's open source. There's also [the old version of AntiRSI](https://github.com/onnlucky/AntiRSI).

Personally I'd much prefer the system to send some events to the app instead of the app polling and juggling the timeouts—IMO it leaves less chance for bugs and potentially needs less fine adjustment.

**Comment by hovancik** [comment] 2017-10-16 06:45
@decadent thanks for feedback and links, I will check them out. 

natural break should work like this: if you are idle longer than 20 seconds, it starts natural break. if there is a break/microbreak during this time, it will go on normally as planned. If you are on natural break longer than your break duration (5 mins by default), stretchly will clear the break planner and no more breaks will be starting. After you come back from idle time, the breaks will "reset". 

Also one thing that might not be obvious: be default, idle time detection is turned off, so you need to turn it on in settings. 

ad break after you come back: right now, stretchly can detect when osx system goes to "sleep". There is a notification shown, telling that `The system is resuming`.

**Comment by hovancik** [comment] 2017-10-16 08:14
@decadent also:  I am force-pushing to that branch so please make sure you have the latest version. The way I do it is to first `git fetch origin` and then `git reset --hard orgin/feature/natural-breaks-manager`

**Comment by decadent** [comment] 2017-10-16 14:24
> Also one thing that might not be obvious: be default, idle time detection is turned off, so you need to turn it on in settings

Ah heck, I somehow missed that completely. Disregard my previous comment then.

(Though, this feature is ubiquitous in time trackers and break reminders and IMO obviously useful, so I'd suggest turning it on by default.)

**Comment by hovancik** [comment] 2017-10-16 14:33
That's good idea. What do you think about adding notification when natural break is finished saying sth like `Natural break finished.` or `Natural break finished. You've been idle 5 minutes.`

**Comment by decadent** [comment] 2017-10-16 14:42
Absolutely unnecessary. The app should 'just work' following the user's natural behavior, without getting the interface in the way other than the break window as the main feature. Resetting the breaks after an off-time is pretty much expected behavior, since the whole purpose of the app is to track the user's work time.

**Comment by hovancik** [comment] 2017-10-23 17:50
merged.

**Closed by hovancik** 2017-10-23 17:50 UTC
Labels: enhancement
