### ISSUE TITLE
Better integration into Gnome Shell Environment

### ISSUE THREAD

**Issue by 183amir** [hovancik/stretchly#44] opened 2016-11-25 23:11 UTC
Is it possible to have [d-bus](https://www.freedesktop.org/wiki/Software/dbus/) available in the app?
The idea is to create a gnome shell applet for this app which is only possible through dbus.
An example for workrave is here: https://github.com/rcaelers/workrave/blob/branch_v1_10/frontend/applets/gnome-shell/src/extension.js

**Comment by 183amir** [comment] 2016-11-25 23:16
More info: https://developer.gnome.org/gio/unstable/GDBusConnection.html Javascript bindings are also available.

**Comment by hovancik** [comment] 2016-11-26 11:32
I'll need some time to read about it. 

gnome shell applet =  GNOME Shell Extensions (https://extensions.gnome.org/)?

**Comment by 183amir** [comment] 2016-11-26 12:05
yes

**Comment by hovancik** [comment] 2016-11-28 16:57
So from what I understand, it's something like electrons IPC (https://github.com/electron/electron/blob/master/docs/api/ipc-main.md) 

What is the reason to build Gnome extension when we have electron? I would rather build something with electron so it's on all platforms, rather then only on Linux.

**Comment by 183amir** [comment] 2016-11-28 17:31
This will replace the tray icon in the gnome shell environment.
Tray icons are deprecated in Gnome Shell and your app is mainly (only) managed through its tray icon.
The idea is to show an applet on top of the screen which is only possible through a gnome shell extension. Like the timer and coffee icon shown below from Workrave.
![image](https://cloud.githubusercontent.com/assets/5738695/20678287/6fee2b4c-b596-11e6-82ef-984352030845.png)
And then you can have a settings or main page.
Have you tried reviewing Workrave? It works on all platforms.
I think you can get good ideas from it.

**Comment by 183amir** [comment] 2016-11-28 17:36
So why do you need Dbus? because your gnome-shell extension will run in another process (in gnome shell process itself) and you will need a way to get information from your main app (like how much is left till the next break) in order to show it on the applet.
But anything that does inter-process communication and is supported in Gnome shell is feasible not just DBus. But, DBus is the only one that I know which is working.

**Comment by hovancik** [comment] 2016-11-29 09:01
Have you tried this https://extensions.gnome.org/extension/712/traytop/ or https://extensions.gnome.org/extension/1031/topicons/? 

From my point of view integrating dbus and creating extension would take a lot of time. I believe it's something that maybe electron should do? Maybe we should create issue on electron and ask them to support Gnome way of handling tray?

**Comment by 183amir** [comment] 2016-11-29 09:28
Yes, those extensions work but not perfectly. I am talking about design philosophy of your app :)
Tray icons, while easy to implement, are not really good design choices.
IMHO, your app needs a main window which can be activated by running the app again (or through its gnome applet). When you have the main window, you can make the tray icon optional.

Also, as you can see an applet does much more than a simple icon and menu. It can show a timer for example which I think is necessary for your app. For example, when I use Workrave, it does not pop up anything but instead it shows me how much time I have till my next break.
If I don't take a break, it will show me how much time is passed since my break's deadline:
![image](https://cloud.githubusercontent.com/assets/5738695/20703928/e4c3be82-b61d-11e6-9df8-a690453424a6.png)

This way, IMHO, is much less intrusive than popping out a window and breaking my focus.
Also, if I feel tired and I see I have only a few minutes left till my next break, I will just start a break right away. BTW, this timer information can also be shown in the main page too.

**Comment by hovancik** [comment] 2016-11-30 07:28
To be honest, my plan with stretchly is to be intrusive, because it solves the problem that I have: can't force myself to take breaks. And I also want it to be minimalistic, so I don't plan to add any main window. I would like to add time information about when is the next break coming up, but I need to think about the way how to display it. That's because I wanna do it multi-platform, not only Linux Gnome , or KDE or so. Maybe small window on the top right corner of screen that people can turn on if they would like to see it.

**Comment by 183amir** [comment] 2016-11-30 09:34
> To be honest, my plan with stretchly is to be intrusive, because it solves the problem that I have: can't force myself to take breaks.

That's ok. As I said I set Workrave to silent mode otherwise it can be very intrusive too.

> Maybe small window on the top right corner of screen that people can turn on if they would like to see it.

This can be serve the purpose of a main screen as well.

IMHO, multi-platform does not mean do the same thing for every platform. Some design ideas don't work for other platforms. You'll end up with having a semi-working interface on all platforms. Interfaces that just don't fit with the rest of the apps in the platform.
I don't think doing a couple of extra things for some platforms so that they fit better is a bad idea.

Also, once we have the dbus support in the main process, we can have gnome-shell extension, Ubuntu Unity and KDE appindicators for the app too in either Stretchly or in a totally different package.

**Comment by hovancik** [comment] 2016-11-30 15:42
How would you image "silent mode" should be with stretchly? I like that idea. 

I am a little bit hesitant with adding dbus because right now I have no npm package as dependency, and I am trying to keep it that way (It sometimes causes troubles with packaging from what I hear on electrons slack).

**Comment by 183amir** [comment] 2016-12-01 09:32
Good question, I have to give it a little thought.

**Comment by 183amir** [comment] 2016-12-08 08:23
A silent mode is only possible when you have some way of indicating the breaks' status.
The minimal way that is possible through the app now is I think to change the color of the tray icon to something like green and red to show that when you are in the timer.
Another approach would be to push a silent notification (when the timer is up) so that it would show up in the notification center assuming that OSes support that.

**Comment by hovancik** [comment] 2016-12-12 08:13
I'm busy right now, but I will think about it as well.

**Comment by wangzk** [comment] 2017-01-16 07:49
@183amir 
Can your stretchly pop up normally in Gnome Shell? I am using Arch Linux and I find that stretchly can not pop up but just give a notification in Gnome Shell, thus to see the reminder from  stretchly I have to open the app by myself.

**Comment by hovancik** [comment] 2017-01-16 07:52
@wangzk what version do you have? (os, gnome, stretchly)? I'll in virtualbox

**Comment by 183amir** [comment] 2017-01-16 09:07
@wangzk I had the same problem but I am not using stretchly anymore.

**Comment by wangzk** [comment] 2017-01-17 09:15
@hovancik Hi, I am using Arch Linux and Gnome Shell 3.22.2. I see Fedora 25 has the Gnome Shell 3.22.2 version and maybe it is enough to reproduce the problem.

By the way, the tips from stretchly is funny :)

**Comment by hovancik** [comment] 2017-01-18 08:34
@wangzk thanks ;]  I've tried and you are right about Gnome Shell. Will try to find fix.

**Comment by hovancik** [comment] 2017-01-18 20:11
@wangzk seems that this a Gnome "feature":  https://major.io/2015/07/06/allow-new-windows-to-steal-focus-in-gnome-3/ or http://superuser.com/questions/644850/disable-window-is-ready-notification-in-gnome-shell

**Comment by wangzk** [comment] 2017-01-19 01:43
@hovancik Thanks for your time to investigate this problem and the blogs you find solve the problem. Finally I can happily use stretchly in Gnome Shell again!
Thanks a lot :+1:

**Comment by hovancik** [comment] 2017-01-19 06:25
@wangzk welcome ;] which solution worked for you?

**Comment by wangzk** [comment] 2017-01-19 07:44
@hovancik I use the dconf-editor way as suggested in the first blog :)

**Comment by hovancik** [comment] 2017-01-19 08:31
@wangzk great, glad it works

**Comment by hovancik** [comment] 2017-01-19 08:33
I am closing this issue: 
- I am not planning to do d-bus integration 
- adding some kind of `silence mode` will be added to TODO
- Gnome shell not opening break window was resolved as well

**Closed by hovancik** 2017-01-19 08:33 UTC

**Comment by decadent** [comment] 2017-10-06 20:37
> I would like to add time information about when is the next break coming up, but I need to think about the way how to display it.

In OSX that's better done with indication in the dock icon. AntiRSI does this perfectly with the two circular progress bars:

![AnsiRSI icon screenshot](https://i.imgur.com/0UO8Xn8.png).

<br/>

Top bar icons are a prime space on Mac, hence the existence of Bartender.
