### ISSUE TITLE
[Bug]:   "Stretchly.app" is damaged and can't be opened.  You should move it to the Bin.

### ISSUE THREAD

**Issue by adamshand** [hovancik/stretchly#1128] opened 2022-03-23 00:42 UTC
### Version

- [X] I'm using version 1.10.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS 12.2.1

### Reproduction steps

Downloading v1.10 of Stretchly either via Homebrew or Github releases (ARM version) results in this message:

> "Stretchly.app" is damaged and can't be opened.  You should move it to the Bin.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/130651/159599543-4e2a55c5-38cb-4e5c-b401-1f46e048791d.png">

This is on an M1 MacBook Air (2020).

Downloading v1.9 via Github releases works fine.

### Expected Behavior

.

### Actual Behavior

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SHEENSHEELLA** [comment] 2022-03-23 11:57
The same problem. MacBook Pro M1 (2020). MacOS Monterey 12.3

**Comment by Josephfilbert** [comment] 2022-03-23 13:44
Yes same problem, I thought the brew cask is corrupted. For now I stick to 1.10.0 x86 version.
As the 1.10.0 x86 version works normally.

**Comment by hovancik** [comment] 2022-03-29 14:12
Did you guys install in a way that Readme suggests? https://github.com/hovancik/stretchly#application-signing=

**Comment by adamshand** [comment] 2022-03-29 20:54
Sorry, I missed the M1 instructions.  Just installed v1.10 with Homebrew using `--no-quarantine` and it seems to be working fine.  

It's weird, though I've never had to do that with any other app installed via Homebrew?  Normally I just get a prompt to approve that it's an unsigned app and once approved it runs without problems.

**Comment by hovancik** [comment] 2022-03-30 12:22
From what I understood, this is a new requirement from Apple for apps for M1 with M1 build.

I don't have M1, though, and M1 build/brew cask was added by community. 

I'll close this, then. In past I tried to register for Apple dev account to publish Stretchly properly, but Apple declined it.

**Closed as completed by hovancik** 2022-03-30 12:22 UTC

**Comment by SHEENSHEELLA** [comment] 2022-07-07 09:51
In my case. This command ''brew install --cask --no-quarantine stretchly" works, but I can't use this app, settings don’t work. App closes and that's all.

**Comment by hovancik** [comment] 2022-07-11 10:18
@SHEENSHEELLA can you try running it from command line and show the logs here? Just type `stretchly` and hit enter

**Comment by SHEENSHEELLA** [comment] 2022-07-11 11:25
@hovancik
[2022-02-16 13:34:49.638] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
[2022-02-17 13:20:05.936] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
[2022-02-18 13:39:04.797] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.9.0)
[2022-02-20 13:54:02.395] [error] TypeError: Failed to fetch
    at VersionChecker.latest (/Applications/Stretchly.app/Contents/Resources/app.asar/utils/versionChecker.js:3:12)
    at EventEmitter.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/process.js:24:10)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:73:1017)
[2022-02-22 13:54:03.148] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.10.0)
[2022-03-16 17:53:02.098] [info]  Stretchly: checking for new version (local: v1.9.0, remote: 1.10.0)
[2022-03-23 14:48:03.592] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-03-23 14:50:28.673] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-07 12:30:24.118] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-07 12:31:01.346] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-07 12:32:22.376] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-07 12:45:22.186] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-11 13:29:04.443] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-11 13:47:26.955] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)
[2022-07-11 14:16:10.442] [info]  Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)

**Comment by hovancik** [comment] 2022-07-14 13:13
@SHEENSHEELLA so what happens exactly? `stretchly` command exits after ` [info] Stretchly: checking for new version (local: v1.10.0, remote: 1.10.0)`? I am confused to see different dates and times there, as I would expect to see only one.

**Comment by SHEENSHEELLA** [comment] 2022-07-14 14:33
@hovancik 
1. I had found Strechly and installed version 1.9.0. It worked very well. But one moment, Strechly had been got update and stoped work. I tried reinstall some times.
2. Link for video with my problem: https://drive.google.com/file/d/1k8yHFJhQ1pDxakyeAwHhuUpF_kAeSPWR/view?usp=sharing

**Comment by hovancik** [comment] 2022-07-22 09:46
@SHEENSHEELLA thanks! Could you please record the same but starting the Stretchly app from Terminal with `stretchly` command? 

Unfortunatelly I do not have MacBook Pro M1 (2020) with MacOS Monterey so I am not able to reproduce on it.

**Comment by SHEENSHEELLA** [comment] 2022-07-22 21:04
@hovancik
Is this what you need?
MacOS Monterey 12.5
Link: https://drive.google.com/file/d/14PgEUlz91pCQmLSQvAt6fqH7gu1w-naY/view?usp=sharing

**Comment by hovancik** [comment] 2022-07-23 09:05
Thanks! 

So the Preferences crashes, but the app keeps running? That's weird. I am on older Mac (pre M1) and all is fine. 

I have found a way how to run app from command line, can you try and see if any errors show? 

`/Applications/Stretchly.app/Contents/MacOS/Stretchly`

**Comment by SHEENSHEELLA** [comment] 2022-07-24 13:31
@hovancik I used this command /Applications/Stretchly.app/Contents/MacOS/Stretchly
Link: https://drive.google.com/file/d/1efItN3q0BvKoK0x0ItdjCiKzotUgA-8W/view?usp=sharing

**Comment by hovancik** [comment] 2022-08-06 11:53
Thanks! I was able to reproduce when I have 2 screens and I rescale the 2nd one to some small size. This happens on 1.10 but not on my local developement version, so 🤞 . New version is hopefully OK.

**Comment by SHEENSHEELLA** [comment] 2022-08-08 09:21
@hovancik  Thanks bro! It works. I am using 2 screens :) I’ll be observing the program.
