### ISSUE TITLE
[Bug]: MacOSX - App icon shows in Dock's recent apps area

### ISSUE THREAD

**Issue by lululemon-leonardomorelli** [hovancik/stretchly#1015] opened 2021-08-11 13:55 UTC
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### Reproduction steps

1. Dock option "show recent applications" must be checked.
2. When a break happens, Stretchly icon appears in the recent apps area.

...
**Reproduces how often:** 100%

### Expected Behavior

It may not be a bug, but it would be better **not adding** the icon to the Dock.
For example, the preferences window doesn't add the icon to the Dock.

### Actual Behavior

The icon remains in the recent apps area of the Dock.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2021-08-16 12:19
Can you show me screenshot of reproduction? I am not using macOS day to day so not sure what you mean by "show recent applications" and where the icon appears :)

**Comment by lululemon-leonardomorelli** [comment] 2021-08-16 12:48
Sure, here it is 
![Screen Shot 2021-08-16 at 09 44 56](https://user-images.githubusercontent.com/54042677/129566086-b93a5e7f-c83a-4c47-85e6-b0056de4ab07.png)

**Comment by hovancik** [comment] 2021-08-16 13:46
Hi, so I have that checked in macOS preferences but can't reproduce :( 

Are you really on Stretchly 1.7? Because I am disabling dock icon in the code (since version 1.2). If you have 1.7, the only thing I can think of is trying to fully remove Stretchly (let's say wit appcleaner https://freemacsoft.net/appcleaner/) and then installing it again. (I have seen cases when upgrading app did not  work correctly for some people and they seen old behaviour)

**Comment by lululemon-leonardomorelli** [comment] 2021-08-16 17:35
I removed the app and also removed settings from "Application Support" and started over.
Version is 1.7 latest one.
The icon still appears in the dock recent apps area, if I remove it, it appears again in the next break.

**Comment by hovancik** [comment] 2021-09-11 09:50
Sorry, but no idea why it's there :(

**Comment by hovancik** [comment] 2022-12-22 12:34
Hi, is this still an issue with latest? Let me know if I should reopen.

**Closed as completed by hovancik** 2022-12-22 12:34 UTC
Labels: help wanted, old version
