### ISSUE TITLE
[Bug]: Old notifications get stacked in the notification centre

### ISSUE THREAD

**Issue by northen-mindset** [hovancik/stretchly#966] opened 2021-05-29 14:42 UTC
### Version

- [X] I'm using version 1.7.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2, OS build 19042.985

### Reproduction steps

1. Run Stretchly for a long time, allow several breaks to pass.
2. Don't dismiss (click) upcoming break notifications.

**Reproduces how often:** always

### Expected Behavior

Break notifications do not represent any value and should not be kept in the notification center. Some apps do so, notifications just appear on the screen and not kept after disappearing.

### Actual Behavior

All the previous notifications are stacked in the notification center:
![Screenshot_88](https://user-images.githubusercontent.com/6065071/120074328-7beb2e00-c0c6-11eb-9637-a303efb5b208.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamP12345-TheReal** [comment] 2021-05-30 13:37
I have the same issue

**Comment by hovancik** [comment] 2021-06-04 09:05
I don't have Windows but on MacOS it is working the same and I think it is expected behaviour: I did not interact with the notification so OS is keeping them for me in the notification center: 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/4745859/120776605-b7518680-c524-11eb-9824-3bee04976660.png">

I am seeing the same for any other app that uses system notifications.

**Comment by northen-mindset** [comment] 2021-06-04 10:38
Some applications, WhatsApp desktop for example, shows the banner (floating notification), but when it disappears after several seconds, the notification does not stay in the action center. Therefore, at least Windows API allows for implementing such a behavior. And this is quite expected for some applications, I'd say. Especially for Stretchly, where old notifications bear no value at all.

As a workaround I have found out that it's possible to turn off the notifications in the Action Center for a particular application while keeping the banners on:
![image](https://user-images.githubusercontent.com/6065071/120788157-58a6ff80-c55a-11eb-900c-f3cd3dd92c2e.png)

But of course it would be expected from the app to behave in such a way out of the box.

P.S.
The settings for WhatsApp are similar:
![image](https://user-images.githubusercontent.com/6065071/120789333-b425bd00-c55b-11eb-9ce2-32045dd57ece.png)

**Comment by hovancik** [comment] 2021-06-04 11:30
Interestingly, many people say that opposite of what you want is a bug: they want notifications to stay but they don't have them staying: https://github.com/electron/electron/issues/3916 

🤷 

I am using https://notifications.spec.whatwg.org/ and there is mention of: 

> User agents should not display non-persistent notification in a platform’s "notification center" (if available). 

https://notifications.spec.whatwg.org/#lifetime-and-ui-integrations

From what I understand, my notifications are non-persistent. I guess noone really cares about the standard and Microsoft / Apple do some things, so you need to set it up on OS level.

**Comment by Chealer** [comment] 2021-08-12 23:33
Thank you for this report @anantakrishna 
Not only does this affect me too, but I would go further and say notifications is not the appropriate mechanism for Stretchly's purpose. Workrave has an equivalent which is not based on the notification center, and it works much better. In addition to avoiding this bug:

1. The remaining time is not frozen, but decreases as time passes.
2. Correspondingly, the light bulb goes less and less happy as the user keeps working towards the limit (yes, it looks silly at first, but it's not that bad once you're used to it).
3. Its apparition produces a distinct sound, which can be changed and even disabled. That sound:
   1. differs from the sound of other notifications, which is particularly important since Stretchly often prompts for breaks when the user is already on break.
   2. [is not the same for mini breaks and rest breaks](https://github.com/hovancik/stretchly/issues/687).
4. When the cursor enters the prompt's zone, the prompt moves to minimize obtrusion.

Should this ticket be retitled to reflect a wider scope, or should a wider ticket be filed to track the general issue?

**Comment by northen-mindset** [comment] 2021-08-13 05:12
@Chealer I believe it deserves a separate ticket. Otherwise renaming this issue will cause confusion because the discussion above is based on the current title.

**Comment by Chealer** [comment] 2021-08-14 20:15
OK @anantakrishna 
Could you still widen the scope a bit by retitling this ticket removing "on Windows 10"?

Point #3.ii is already covered in [a ticket requesting "Different sound for breaks and other for microbreaks"](https://github.com/hovancik/stretchly/issues/687).

**Comment by northen-mindset** [comment] 2021-08-15 15:15
> Could you still widen the scope a bit by retitling this ticket removing "on Windows 10"?

Right, done.

**Comment by ekasprzak** [comment] 2023-03-17 18:13
Same here on Linux (Fedora GNOME) - notifications don't disappear from the "Gnome notifications" at all, every X min I just clear it manually.
I can't see any seetings in GNOME that could resolve it - I can only disable or enable notifications for a specific app and that's it.

**Comment by hovancik** [comment] 2023-03-18 13:16
And how do other apps work? For me, on KDE, it seems to me that all apps' notifications work that way and stay until manually cleared

**Comment by Chealer** [comment] 2023-03-18 20:31
The right question would be how comparable apps work. I unfortunately only evaluated 2 or 3 apps of the kind, but the one I know well, Workrave, which is the reference of the class at least among FLOSS options, does not use notifications to achieve that.

Notifications are a standardized mechanism which must be simpler to implement, but they're unfortunately far from matching a custom handler for this purpose.

@ekasprzak I am afraid there is no way to workaround this as a user. Workrave is far from perfect, but it has a long lead over Stretchly on this issue and several others, so I strongly recommend you evaluate it if you haven't already.

**Comment by ekasprzak** [comment] 2023-03-18 22:36
@hovancik  
Previously, on Ubuntu (GNOME) I was using [SafeEyes](https://github.com/slgobinath/SafeEyes), unfortunately it has no flatpak, snap, AppImage or rpm for my current Fedora, that's why I'm trying out Strechtly right now.

There, there is a notification before and after a break (almost sure it can be customized), but it disappears (as expected for me at least) after a few seconds from the screen and "GNOME "notification center" as well.

@Chealer 
I remember testing Workrave sometime ago, can't remember now what exactly I didn't like, but there was definitely something that made me cross it off the list.

**Comment by hovancik** [comment] 2023-04-06 09:14
I've made some changes in #1296 and after I do not see Notifications in notif center anymore. At least in KDE. Hopefully the same effect will be in other OSes/DEs

**Comment by hovancik** [comment] 2023-04-11 09:27
For Windows OS, this change does not make any difference unfortunately.

**Comment by ekasprzak** [comment] 2023-04-11 14:52
> I've made some changes in #1296 and after I do not see Notifications in notif center anymore. At least in KDE. Hopefully the same effect will be in other OSes/DEs

Yes, it doesn't appear in notification center anymore, so no more of constantly clearing it manually, this is great, thanks @hovancik!

(Fedora 37 Workstation/GNOME)

**Comment by hovancik** [comment] 2023-04-11 16:45
Also testing on macOS and all is fine. So to conclude, macOS and Linux is fine, but Windows doesn't work and Electron is not going to support this: https://github.com/electron/electron/issues/9283

**Closed as completed** 2023-04-11 17:01 UTC
Labels: enhancement, wontfix, electron

**Comment by Chealer** [comment] 2025-02-14 04:00
Many thanks for solving this @hovancik 

> […] Workrave has an equivalent which is not based on the notification center, and it works much better. In addition to avoiding this bug:
> 
>  1. The remaining time is not frozen, but decreases as time passes.
> 
>  2. Correspondingly, the light bulb goes less and less happy as the user keeps working towards the limit (yes, it looks silly at first, but it's not that bad once you're used to it).
> 
>  3. Its apparition produces a distinct sound, which can be changed and even disabled. That sound:
>        
>     1. differs from the sound of other notifications, which is particularly important since Stretchly often prompts for breaks when the user is already on break.
>     2. [is not the same for mini breaks and rest breaks](https://github.com/hovancik/stretchly/issues/687).
> 
>  4. When the cursor enters the prompt's zone, the prompt moves to minimize obtrusion.
> 
> 
> Should this ticket be retitled to reflect a wider scope, or should a wider ticket be filed to track the general issue?

#3.1 is now tracked in ticket #1565 (which also mentions the other points).
