### ISSUE TITLE
[Bug]:   Excessive RAM usage

### ISSUE THREAD

**Issue by smith558** [hovancik/stretchly#939] opened 2021-04-30 13:49 UTC
### Version

- [X] I'm using version 1.6.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Linux

### Operating System Version

Linux 5.11.0-16-generic, Ubuntu 21.04 on Wayland

### Reproduction steps

Stretchy running. No errors in the log.

### Expected Behavior

Not applicable.

### Actual Behavior

The RAM usage of Stretchly seems excessive. I am sure this is quite subjective, however, it seems like a lot. (~ 1.5 GB)
![stretchly_ram](https://user-images.githubusercontent.com/44023416/116700745-0739ac80-a9bf-11eb-92e8-e78d306300a0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2021-05-01 08:48
duplicate of #925

**Closed as completed by hovancik** 2021-05-01 08:48 UTC

**Comment by smith558** [comment] 2021-05-01 13:08
Must have missed the duplicate.
