### ISSUE TITLE
[bug] MacOS fullscreen break not exiting on secondary monitor

### ISSUE THREAD

**Issue by StevenM1** [hovancik/stretchly#903] opened 2021-04-08 08:51 UTC
### Prerequisites

- [√] I'm using latest version: v 1.5.0
- [√] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [√] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Since upgrading to 1.5.0 yesterday, I noticed that fullscreen breaks do not exit properly on my secondary monitor. The standard green Stretchly break screen does disappear, but the screen remains black and set to the Stretchly virtual desktop. I can manually change the virtual desktop back, but I'm guessing this is not intended behavior.

I also noticed that the virtual desktop remains existing on my primary monitor, although I'm not sure if this is intended behavior.

Operating system: macOS 10.15.7 (MacBook Pro 2017 13" non-touchbar two-tb3 ports)

### Steps to Reproduce

1. Have two screens (in my case, an external monitor, the laptop itself serves as the secondary monitor) 
2. Show a break in full screen (eg wait for stretchly or skip to next). Both monitors switch to Stretchly virtual desktops. 
3. Let it finish the countdown
4. The primary monitor automatically goes back to the normal virtual desktop, but the secondary monitor doesn't.

**Expected behavior:** Both screens should return to their original virtual desktop

**Actual behavior:** The primary screen returns to the original virtual desktop, but the secondary screen doesn't.

**Reproduces how often:** Always.

### Additional Information

Even on my primary monitor, Stretchly's virtual desktop is not closed down (see screenshot to clarify what I mean). But I don't know if this is intended behavior.
<img width="2560" alt="Screenshot 2021-04-08 at 10 44 18" src="https://user-images.githubusercontent.com/17780626/113996505-896b0100-9857-11eb-804e-bddf17dac61c.png">

### Debug information

Can't really find much that hints at an error, this morning's logs:

[2021-04-08 09:03:02.917] [info]  Stretchly: loading settings
[2021-04-08 09:03:02.951] [info]  Stretchly: starting Idle time monitoring
[2021-04-08 09:03:02.952] [info]  Stretchly: starting DND monitoring
[2021-04-08 09:13:11.044] [info]  Stretchly: loading settings
[2021-04-08 09:13:11.051] [info]  Stretchly: starting Idle time monitoring
[2021-04-08 09:13:11.051] [info]  Stretchly: starting DND monitoring
[2021-04-08 09:33:01.053] [info]  Stretchly: showing Mini Break notification
[2021-04-08 09:33:11.464] [info]  Stretchly: showing window 1 of 2
[2021-04-08 09:33:11.552] [info]  Stretchly: starting Mini Break
[2021-04-08 09:33:11.676] [info]  Stretchly: showing window 2 of 2
[2021-04-08 09:33:31.561] [info]  Stretchly: finishing Mini Break

Which seems normal to me. I did find a TypeError in yesterday's logs (also had the bug then):

[2021-04-07 15:58:20.095] [info]  System: resume or unlock
[2021-04-07 15:58:20.099] [info]  Stretchly: resuming breaks
[2021-04-07 15:58:22.237] [error] TypeError: windowArray is not iterable
    at closeWindows (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:145:24)
    at breakComplete (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:652:10)
    at postponeBreak (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:677:15)
    at IpcMainImpl.<anonymous> (/Applications/Stretchly.app/Contents/Resources/app.asar/main.js:1050:3)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)
[2021-04-07 15:59:30.279] [info]  Stretchly: loading settings
[2021-04-07 15:59:30.285] [info]  Stretchly: starting Idle time monitoring
[2021-04-07 15:59:30.285] [info]  Stretchly: starting DND monitoring
[2021-04-07 16:19:20.300] [info]  Stretchly: showing Mini Break notification
[2021-04-07 16:19:30.593] [info]  Stretchly: showing window 1 of 2
[2021-04-07 16:19:30.659] [info]  Stretchly: starting Mini Break
[2021-04-07 16:19:30.727] [info]  Stretchly: showing window 2 of 2
[2021-04-07 16:19:32.628] [info]  Stretchly: postponing Mini Break
[2021-04-07 16:21:22.629] [info]  Stretchly: showing Mini Break notification
[2021-04-07 16:21:32.933] [info]  Stretchly: showing window 2 of 2
[2021-04-07 16:21:33.007] [info]  Stretchly: showing window 1 of 2
[2021-04-07 16:21:33.128] [info]  Stretchly: starting Mini Break
[2021-04-07 16:21:53.132] [info]  Stretchly: finishing Mini Break

Other debug info:
breakPlanner: {reference: startMicrobreakNotification,
timeleft: About 15 minutes remaining,
breakNumber: 3,
postponesNumber: 0,
Do Not Disturb: false}

settingsFile: /Users/steven/Library/Application Support/Stretchly/config.json

logsFile:  /Users/steven/Library/Logs/Stretchly/main.log
Node.js: 14.16.0
Chromium: 89.0.4389.90,
Electron: 12.0.2

Settings:
{
    "microbreakDuration": 20000,
    "microbreakInterval": 1200000,
    "breakDuration": 60000,
    "breakInterval": 3,
    "breakNotification": true,
    "microbreakNotification": true,
    "breakNotificationInterval": 30000,
    "microbreakNotificationInterval": 10000,
    "microbreak": true,
    "break": true,
    "microbreakStrictMode": true,
    "breakStrictMode": true,
    "morningHour": 6,
    "mainColor": "#478484",
    "audio": "silence",
    "fullscreen": true,
    "ideas": true,
    "naturalBreaks": true,
    "allScreens": true,
    "useIdeasFromSettings": false,
    "language": "en",
    "notifyNewVersion": true,
    "isFirstRun": false,
    "posLatitude": 0,
    "posLongitude": 0,
    "useMonochromeTrayIcon": true,
    "breakIdeas": [  ...   ],
    "microbreakIdeas": [   ...   ],
    "microbreakPostpone": true,
    "breakPostpone": true,
    "microbreakPostponeTime": 120000,
    "breakPostponeTime": 300000,
    "microbreakPostponesLimit": 1,
    "microbreakPostponableDurationPercent": 30,
    "breakPostponesLimit": 1,
    "breakPostponableDurationPercent": 30,
    "useMonochromeInvertedTrayIcon": false,
    "silentNotifications": false,
    "monitorDnd": true,
    "microbreakStartSoundPlaying": false,
    "breakStartSoundPlaying": false,
    "volume": 1,
    "naturalBreaksInactivityResetTime": 300000,
    "themeSource": "system",
    "endBreakShortcut": "CmdOrCtrl+X",
    "transparentMode": false,
    "opacity": 0.9,
    "breakWindowWidth": 0.85,
    "breakWindowHeight": 0.85,
    "checkNewVersion": true,
    "showBreaksAsRegularWindows": false,
    "appExclusions": []
}

**Comment by csducate** [comment] 2021-04-08 14:56
I just updated and am also having this issue using 2 monitors. However, when I toggle off the setting "Show breaks on all monitors", the problem is reproduced on the monitor of my main machine.

Operating system: macOS 11.2.3 (MacBook Pro, Retina, mid-2015, 15-inch) with Dell 2nd monitor (DELL SP2309W 23-inch)

**Comment by macouen** [comment] 2021-04-09 02:34
+1

**Comment by hovancik** [comment] 2021-04-09 07:03
I do not remember changing anything with 1.5 so must be due to upgrade of electron to version 12 :( Might also be related to https://github.com/electron/electron/issues/25427

**Comment by StevenM1** [comment] 2021-04-09 07:10
Bummer! I'll just downgrade to 1.4.0 for now and keep an eye on this in the meantime. And thanks for developing this app, it's really great!

I'm guessing this won't help but just for the sake of completeness: I noticed it's not necessarily the _secondary_ monitor that remains stuck on the Stretchly virtual desktop / black screen, but it's the monitor that's not currently in focus. Ie if I'm briefly working on my secondary screen and the break pops up, it's actually the primary monitor that remains stuck on the black screen.

**Comment by HugooB** [comment] 2021-04-09 07:31
Similar problem here!

**Comment by derekazhang** [comment] 2021-04-09 08:51
+1

**Comment by cooldevcodes** [comment] 2021-04-10 08:09
Same problem here.

Even worse as I connect my MacBook Pro with an external monitor. When the problem happens, if I close the MacBook Pro's lid to use the external monitor only, if I switch between desktops then my external monitor also stucks with back screen.

**Comment by hovancik** [comment] 2021-04-10 10:44
So I've spend few hours debugging but can't find what's causing it. Also tried with simple electron app and everything worked fine there :( So no idea basically... 

As a partial workaround I would use non-fullscreen breaks and possibly make the window bigger via advanced settings: https://github.com/hovancik/stretchly#break-window-size-

**Comment by yanhao-li** [comment] 2021-04-10 16:13
same issue here, I'm going to temporarily switch to non-fullscreen.
it's a great app, thank you for the efforts!

**Comment by pstagg** [comment] 2021-04-11 05:55
+1 - Can't add much to the conversation. I'm on a 2017 MacBook pro running Big Sur 11.2.3 (but the problem started before I updated). I have an exterior monitor which when plugged in is the primary monitor. When running Stretchly in full-screen mode the primary screen is exited cleanly but the secondary ends up blank/black. I have to use Mission Control and foreground/background another app to get the screen back. The only other thing I can report is that the issue only seems to happen when "Displays have separate Spaces" is checked in Mission Control's settings.

**Comment by hovancik** [comment] 2021-04-11 09:59
So I think I found the culprint: #875

I'll investigate the the fix when I have more time.

**Comment by hovancik** [comment] 2021-04-11 10:01
Note to self: 

commenting this code makes it work: 

```
    if (microbreakWinLocal) {
      // microbreakWinLocal.on('close', (e) => {
      //   if (!appIsQuitting) {
      //     e.preventDefault()
      //   }
      // })
      microbreakWinLocal.on('closed', () => {
        microbreakWinLocal = null
      })
    }
```

**Closed as completed** 2021-04-12 08:50 UTC

**Comment by HugooB** [comment] 2021-04-12 09:42
Great work, thanks @hovancik !
