### ISSUE TITLE
Javascript Error after Update with Brew

### ISSUE THREAD

**Issue by kajatiger** [hovancik/stretchly#766] opened 2020-11-12 23:42 UTC
I just upgraded stretchly running `brew update && brew upgrade --cask` and am getting error messages. Mac OS Catalina. It is a Javascript error.

<img width="432" alt="Bildschirmfoto 2020-11-13 um 00 33 26" src="https://user-images.githubusercontent.com/15628617/99009335-327f2b00-2548-11eb-9b7f-a2fc5970fd9c.png">

### Prerequisites

- [x] I'm using latest version: v 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

**Reproduces how often:** When clicking "ok" on the error message it reappears as long as I have the terminal with brew open.

**Comment by hovancik** [comment] 2020-11-13 16:17
Hi @kajatiger , did you restart the app after upgrading?

**Comment by hovancik** [comment] 2020-11-13 16:20
Or better, when upgrading, Stretchly should be quit. I don't think `brew` takes care of that.

**Comment by idbrii** [comment] 2021-02-09 05:25
I had the same issue and restarting Stretchly (quit from menu and then run the .app) fixes it. Seems to be caused by files changing while stretchly is running.

**Comment by hovancik** [comment] 2021-02-14 11:11
Yep. I've tried to search the docs of Brew whether I can enable automatic restart of the app but did not find it, so will close this. Readme mentions to close the app, first. 

https://github.com/hovancik/stretchly#macos

**Closed by hovancik** 2021-02-14 11:11 UTC
