### ISSUE TITLE
Stretchly Intercepting Ctrl + X on Windows 10 on v0.21.0

### ISSUE THREAD

**Issue by ketura** [hovancik/stretchly#497] opened 2019-11-20 17:28 UTC
### Prerequisites

- [✓] I'm using latest version: v0.21.0 
- [✓] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

For some time I've had an intermittent issue where the ctrl + x hotkey (commonly "cut to clipboard") stopped working in random applications.  Finally I got tools installed to track the problem when next it happens.  Today I once again ran into the issue, started up Spy++, and used its message monitoring capabilities to track the WM_HOTKEY message all the way to Stretchly:

![image](https://user-images.githubusercontent.com/1814132/69260568-b8f76b80-0b85-11ea-843f-c6d81c62be88.png)

Sure enough, when I closed Stretchly the hotkey interception went away.

Now, while typing all this up I was going through the issue checklist and saw that version 0.21.0 was supposed to have `Fixed: Ctrl+X global shortcut not being released after Reset breaks and Skip to`, but I think a logic branch was missed.

After playing with it a bit, it seems that if "Reset breaks" is used while a (regular) break is currently on the screen, it causes the issue.  Skipping during a microbreak seems to do nothing.  

When manually skipping to the next full-sized break and hitting Reset Breaks, I sometimes get the following error message as soon as I next hit ctrl + x:

![image](https://user-images.githubusercontent.com/1814132/69261361-058f7680-0b87-11ea-899e-bba4e9c1ddba.png)

In which case ctrl + x is not bound, but if the error message doesn't show, ctrl + x is bound until Stretchly is restarted.  I suspect the behavior is slightly different when a break happens naturally rather than manually invoked, but did not confirm.  

Operating system: Windows 10 Pro 1809

### Steps to Reproduce

1. Skip to the next break (not microbreak)
2. Reset breaks using the taskbar icon context menu while the window is on-screen
3. Use the ctrl + x hotkey.  If an error message does not show, ctrl + x is now bound permanently by Stretchly until restart.  

**Expected behavior:** ctrl + x is never bound except when the break screen is showing

**Actual behavior:** ctrl + x is intercepted and unusable by other applications

**Reproduces how often:** possibly every time a (full-sized) break is skipped, modulo whatever controls that error message showing up

**Comment by ketura** [comment] 2019-11-20 19:21
There's something about this that makes break/microbreak timing go haywire as well; I have my micro/breaks set to come up every 20 minutes, and I keep getting them at random single-digit-minute intervals, probably a side-effect of that null reference exception.

**Comment by hovancik** [comment] 2019-11-21 12:04
Thanks for the report! I will look into it. I might have missed something as you say.

**Comment by hovancik** [comment] 2019-12-03 08:33
Testing on mac and linux and can't reproduce. Will have to get my hands on some Windows machine.

**Comment by hovancik** [comment] 2019-12-17 08:15
@ketura I am trying in Windows 10 1909 and can't reproduce ;[ Can you try updating the windows if possible? Also maybe the update of stretchly didn't go that well and you might have old code still there?

**Comment by aleksey-hoffman** [comment] 2021-03-02 10:40
@hovancik I see this issue on the latest Win10 as well. The app is not unregistering the `endBreakShortcut` shortcut in some cases.

I would suggest to not use a global shortcut at all, but rather create a window keydown listener in the renderer process:
```js
document.addEventListener('keydown', handleKeydown);

function handleKeydown (event) {
  if (isEndBreakShortcut(event)) {
    postpone()
  }
}
```

It will only work when the app window is focused, which is perfect for this case.

Or if you want to keep using a global shortcut for this, set a timer for the unregistering function when the break window is opened, so the shortcut always gets unregistered as soon as the postpone button disappears:

```js
let timers = {
  endBreakShortcut: null
}

function functionThatDisplaysTheBreakWindow () {
  timers.endBreakShortcut = setTimeout(() => {
    globalShortcut.unregister(settings.get('endBreakShortcut'))
  }, breakPostponeTimeout)
}
```

**Comment by hovancik** [comment] 2021-03-07 10:37
@aleksey-hoffman I had it like that before but it didn't work reliably. There are also cases when window is not focused.

**Comment by aleksey-hoffman** [comment] 2021-03-17 20:32
@hovancik could you add an option to disable global shortcut from being registered entirely? I like the app but this bug is very annoying

**Comment by hovancik** [comment] 2021-03-25 14:36
@aleksey-hoffman what kind of error are you getting?

**Comment by hovancik** [comment] 2021-03-25 14:39
could you paste the log from around the time the issue happens? Now that we have it, I would like to take a look.

**Comment by aleksey-hoffman** [comment] 2021-03-25 14:58
@hovancik I don't have logs, but it's most likely the same thing described by the OP. It happens a few times a week. Some event causes `Ctrl + X` shortcut to stop working system wide until you terminate all the Stretchly's app processes.

If you could add an option to disable the shortcut from being registered entirely, that would be great.

BTW, what are the complications with the "local window shortcuts" method you mentioned above? Could it not be fixed by programmatically focusing the window with `mainWindow.focus()`?

**Comment by hovancik** [comment] 2021-03-25 15:37
There's a option which tells Stretchly to have breaks as regular windows, not on top, etc. 

By logs I mean Stretchly's logs. If you go to the Preferences -> About and hit `Ctrl/Cmd+D` you'll see the location of logs file. 

Esiest would be to add new option to disable shortcuts, or maybe to change the code so that empty string is interpreted as "do not set shortcut".

**Comment by hovancik** [comment] 2021-04-23 12:30
Adding option to set shortcut to `""` and thus disable it in #929

**Comment by aleksey-hoffman** [comment] 2021-04-23 12:40
@hovancik thank you

**Closed** 2021-05-18 11:12 UTC
Labels: bug
