### ISSUE TITLE
[Bug] Stetchly not displaying on primary monitor 

### ISSUE THREAD

**Issue by mwoz123** [hovancik/stretchly#1109] opened 2022-03-07 11:41 UTC
In Windows 10, Strechly Break window is displayed in the second monitor (not the one that has been selected as "primary" monitor) :

![image](https://user-images.githubusercontent.com/4487025/157023242-a4837e6f-bde4-4ce8-ac5c-ce5cf19665f6.png)

It is displayed on Secondary (E-ink) monitor - I tried to move the window with `Win + arrow left` / `Win+shift+arrow left` but didn't work

My configuration 
- Stechly version 1.10.0
- Window 10
- unselected:
"Shows breaks on all monitors" 
![image](https://user-images.githubusercontent.com/4487025/157023974-acc5ba35-935b-451d-82d1-c58f3f9454a3.png)

**Comment by hovancik** [comment] 2022-03-13 10:55
could you please paste your config?

**Comment by mwoz123** [comment] 2022-03-14 17:31
```
{
	"microbreakDuration": 20000,
	"microbreakInterval": 1800000,
	"breakDuration": 300000,
	"breakInterval": 1,
	"breakNotification": true,
	"microbreakNotification": true,
	"breakNotificationInterval": 30000,
	"microbreakNotificationInterval": 10000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": false,
	"breakStrictMode": false,
	"morningHour": 6,
	"microbreakPostpone": false,
	"breakPostpone": true,
	"microbreakPostponeTime": 120000,
	"breakPostponeTime": 300000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 30,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 30,
	"mainColor": "#ffffff",
	"transparentMode": true,
	"opacity": 0.9,
	"audio": "crystal-glass",
	"volume": 1,
	"fullscreen": false,
	"ideas": true,
	"naturalBreaks": true,
	"naturalBreaksInactivityResetTime": 300000,
	"allScreens": false,
	"useIdeasFromSettings": false,
	"language": "en",
	"notifyNewVersion": false,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": false,
	"useMonochromeInvertedTrayIcon": false,
	"silentNotifications": false,
	"monitorDnd": true,
	"microbreakStartSoundPlaying": true,
	"breakStartSoundPlaying": true,
	"themeSource": "system",
	"endBreakShortcut": "Ctrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": true,
	"breakIdeas": [
		{
			"data": [
				"Not alone",
				"Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better. Taking breaks together increases productivity."
			],
(...)
	],
	"microbreakIdeas": [
		{
			"data": "Go grab a glass of water.",
			"enabled": true
		},
(...)
		
	],
	"showBreaksAsRegularWindows": false,
	"appExclusions": [],
	"appExclusionsCheckInterval": 1000,
	"pauseForSuspendOrLock": true,
	"pauseBreaksShortcut": "",
	"resumeBreaksShortcut": "",
	"screen": "primary",
	"timeToBreakInTray": false,
	"currentTimeInBreaks": false
}
```

**Comment by hovancik** [comment] 2022-03-26 15:18
You could try changing value of `	"screen": "primary",` as a workaround: https://github.com/hovancik/stretchly#monitor-to-show-breaks-on-= to 0 or 1 possibly. Looks like bug in electron wrongly choosing what's primary monitor

**Comment by mwoz123** [comment] 2022-03-31 14:35
```
"screen": "1",
```

works for me. @hovancik Thanks:) should I close the bug with workaround or you want it to leave it until resolved ?

**Comment by hovancik** [comment] 2022-04-01 15:16
Let's keep it open, if i ever find time I will try to make some minimal reproducible bug for Electron project.

**Comment by hovancik** [comment] 2023-04-06 12:49
Hi @mwoz123 , I wonder, is this the same issue with latest Stretchly?

**Comment by hovancik** [comment] 2024-02-12 18:36
I don't think I will ever find time to work on this, so closing.

**Closed as completed by hovancik** 2024-02-12 18:36 UTC
Labels: help wanted, electron, upstream, old version

**Comment by mwoz123** [comment] 2024-12-18 09:33
just fyi: on win11 same issue, Strechly version: 1.15.1 but workaround [with](https://github.com/hovancik/stretchly/issues/1109#issuecomment-1084672089) :
> ```
> "screen": "1",
> ```
> 
> works for me. @hovancik Thanks:) should I close the bug with workaround or you want it to leave it until resolved ?
