### ISSUE TITLE
[BUG] Wrong Background Colors

### ISSUE THREAD

**Issue by alabotski** [hovancik/stretchly#1405] opened 2023-11-26 07:20 UTC
### Version

- [X] I'm using version 1.15.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### Advanced Preferences

- [X] I've checked Advanced Preferences

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### Reproduction steps

Background is duplicated
Version 1.15.0 1.15.1

[2023-11-25 10 35 44](https://github.com/hovancik/stretchly/assets/439337/d25388c4-d0e7-4cbe-b031-1321b7fa6353)

### Expected Behavior

The background must be plain

### Actual Behavior

There are two colors on the background

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2023-11-30 12:52
Hi, is this with other language versions as well? Is this for any color or just this one?

**Comment by alabotski** [comment] 2023-12-01 09:42
@hovancik 
Hi
I record small video
https://mega.nz/folder/TV4FmSqZ#tXkYBGh3nzy_dOIVo5WYeQ

**Comment by OlegTopalov** [comment] 2023-12-01 14:24
I have the same issues, however, I'm using English language. Tested on multiple colors

**Comment by hovancik** [comment] 2023-12-11 07:59
@alabotski many thanks! looks like some CSS quirk
@OlegTopalov are you also on Windows 10? 

On Windows 11 everything is fine for me

**Comment by OlegTopalov** [comment] 2023-12-11 08:00
> @alabotski many thanks! looks like some CSS quirk @OlegTopalov are you also on Windows 10?
> 
> On Windows 11 everything is fine for me

yep, win 10

**Comment by OlegTopalov** [comment] 2023-12-11 09:45
> @alabotski many thanks! looks like some CSS quirk @OlegTopalov are you also on Windows 10?
> 
> On Windows 11 everything is fine for me

Btw, noticed, that the issue is not present in Transparent mode. Also, I get some weird ghosting of the tooltip when hovering over Skip text

**Comment by OlegTopalov** [comment] 2023-12-11 13:32
The most weird thing is that when adding DevTools on the page - this issue dissapears, but closing devtools creates similar glitches. I'm not very familiar with Electron development, but it feels, like it's some sort of their rendering issue.
BTW, recorded on upgraded from win10 win11

https://github.com/hovancik/stretchly/assets/26525991/f241ca67-4c1b-45b1-a17d-2e6ee441cd7c

**Closed as completed** 2023-12-15 13:18 UTC
Labels: help wanted
