### ISSUE TITLE
[Bug]:   The dead screen is back

### ISSUE THREAD

**Issue by uahnbu** [hovancik/stretchly#933] opened 2021-04-24 02:41 UTC
### Version

- [X] I'm using version 1.6.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1909

### Reproduction steps

1. When a periodical break end
**Reproduces how often:** About 90% of the time

### Expected Behavior

The screen goes back to normal after the break

### Actual Behavior

The screen goes dead. Keyboard and mouse are still handled but the screen doesn't update. I have to navigate through tabs by using `[Alt]`+`[Tab]` to make the screen redrawn.

### Relevant log output

[main.log](https://github.com/hovancik/stretchly/files/6370271/main.log)

### Preferences

[config.log](https://github.com/hovancik/stretchly/files/6370274/config.log) (I changed the filetype as Github doesn't allow uploading `.json` file)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2021-04-24 17:52
Hi @uahnbu . What do you mean by dead screen? Could you be more descriptive? 

Could you also please fill the log output form when issue occurs and your Preferences file?

**Comment by uahnbu** [comment] 2021-04-24 18:08
[main.log](https://github.com/hovancik/stretchly/files/6370271/main.log)
[config.log](https://github.com/hovancik/stretchly/files/6370274/config.log) (I changed the filetype as Github doesn't allow uploading `.json` file)
To be more descriptive, below are some examples:
* I'm on Github commenting then Stretchly shows up for a break. After the break ends, it fades away to show Chrome screen again. However, I cannot scroll or click or move the pointer of the webpage, although the pointer moves to the clicked location after I've applied the fix below.
* I'm watching a video on Youtube. After the break, the Youtube video goes black although it's still playing with sound.

**How I fix it:** Press `Alt`+`Tab`

**Comment by hovancik** [comment] 2021-04-25 14:44
Thanks, please see the Known issues. It links to the comment with possible fix on Chrome side.

**Comment by uahnbu** [comment] 2021-05-13 15:55
Hmm, maybe an update in Chrome enabled the flag again. Now it has worked.

**Comment by uahnbu** [comment] 2021-05-13 15:59
However, in other Web Apps such as VSCode, the problem still exists. How to disable the flags in those apps?

**Comment by hovancik** [comment] 2021-05-13 17:47
Maybe this will help? https://github.com/microsoft/vscode/issues/114459 they seems to mention the same flag

**Comment by ajaxbits** [comment] 2021-06-09 16:36
Also experiencing this issue on Windows 10. Apps which freeze after a fullscreen break reminder in my (unscientific) testing include:
- Todoist
- Slack
- VSCode

**Comment by hovancik** [comment] 2021-06-12 10:24
That sucks, TBH I am not sure what to do :( This must be something between Chrome - Chromium - Electron but not sure how I could make some small reproducible example to report somewhere.

**Comment by senpl** [comment] 2021-06-13 08:07
@ajaxbits fullscreen break reminder - are U sure problem not exist without full screen remainder. Could you turn off fullscrean break remainder and check if problem exist? 
Other thing to try - If this is repeating thing then starting streatchly from command line would at least provide some logs. And this could give some clues where to look. Even better would be source code with debug flags. But getting some sort of logs would be a first step.

**Comment by ajaxbits** [comment] 2021-06-13 16:41
Totally, @senpl. I'll see if I can get some logs.

**Comment by DanRunfola** [comment] 2023-01-11 13:17
I just ran into this, but I know the cause (I think): I am using a folder on a mounted drive, and there is a network connectivity issue ongoing right now.  

So, process to replicate:
1) Open my folder on a mounted NFS drive, open some file inside of it.
2) Swamp your network :) :) 
3) Close VSCODE.  You may have to force close it, as it will complain about being unable to complete backups or some such.
4) Try to open VSCODE again.  You get a black screen, with no means to escape.

**Comment by hovancik** [comment] 2024-12-28 13:08
Hi, I will close this one as noone complained lately, please open new issue with up to date info if this happens again.

**Closed as not planned** 2024-12-28 13:08 UTC
Labels: help wanted, electron, upstream
