### ISSUE TITLE
Show total time at computer in breaks

### ISSUE THREAD

**Issue by marcustrp** [hovancik/stretchly#1035] opened 2021-11-06 20:03 UTC
Hello!

Using Stretchly to remember to get up and move, really like it!

I would like a feature, though: show the total time that the computer has been used today. Let's say I would like to limit my active computer use to 4 hours a day. Stretchlys break windows would be the perfect place for me to see how long I have been using the computer today.

A few different variants that could be shown (all reset at midnight, or maybe custom time, every day):
- total uptime of computer
- total uptime, but excluding idle time (I would use this one, as I want to count for example video games, but not if I leave the computer on while taking a break)
- total uptime, but excluding idle time and Do Not Disturbe mode

Regards,
Marcus

**Comment by hovancik** [comment] 2021-11-28 13:13
Hi, closing this as a duplicate of #266 . Please follow updates there.

**Closed as completed by hovancik** 2021-11-28 13:13 UTC
