### ISSUE TITLE
Weird clicking when using VoiceOver

### ISSUE THREAD

**Issue by jkjustjoshing** [hovancik/stretchly#533] opened 2020-02-21 17:14 UTC
### Prerequisites

- [x] I'm using latest version: 0.21.1 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description
When using VoiceOver, there is a constant clicking sound when the microbreak window is open.

Operating system: macOS 10.15.3

### Steps to Reproduce

1. Enable VoiceOver
2. Wait for (or trigger) a break

**Expected behavior:** VoiceOver announces that it's time to take a break, optionally counting down the seconds (but better to not I'd think?)

**Actual behavior:** A weird clicking sound. My guess is VoiceOver keeps trying to read the content of the popover, but every instant it tries reading it the progress bar ticks farther along, forcing VoiceOver to start over. Only the first fraction of a second of the text reading gets emitted, and it repeats until the window disappears, at which time VoiceOver reads the content of the (now disappeared) window.

**Reproduces how often:** Always

**Comment by hovancik** [comment] 2020-02-23 17:21
Hi @jkjustjoshing and thanks for the report. To be sure, you mean a built-in from Apple? https://en.wikipedia.org/wiki/VoiceOver

note to self: read more here https://github.com/electron/electron/pull/10305

**Comment by jkjustjoshing** [comment] 2020-02-24 14:34
Yep, happens when I have the built-in screen reader enabled.

To be clear, I don't use VoiceOver regularly - I'm a web developer and happened to be doing VoiceOver testing when my Stretchly popover appeared. So I'm not sure what the correct behavior would look like, just that the current functionality seems less-than-optimal.

**Comment by hovancik** [comment] 2022-12-23 15:00
Hi, is still issue with latest? I wonder if I can help here, but not sure.

**Comment by hovancik** [comment] 2023-03-18 15:19
No reply and this is pretty old, so closing. Let me know if this is still an issue

**Comment by jkjustjoshing** [comment] 2023-03-18 15:48
Sorry for not replying. Yes, I just downloaded Stretchly v1.13.1, macOS version 13.2.1 on an M2 Pro Mac. See attached video. Please re-open.


https://user-images.githubusercontent.com/813192/226116111-32cb0bc3-c06b-4b44-b4c4-eb0063abf7da.mov

**Comment by hovancik** [comment] 2023-03-18 17:07
Do you have some specific settings for Voice Over  / Stretchly? 

I am trying to reproduce but I do not get any weird noises.

**Comment by hovancik** [comment] 2023-03-18 17:16
But I think the cause is VoiceOver trying to read time remaining, in your case, so https://github.com/hovancik/stretchly/pull/1288 should help fixing that, if you could try

**Comment by hovancik** [comment] 2023-04-01 18:23
I've merged the change so let's see on the next version :)

**Closed** 2023-04-01 18:23 UTC
Labels: bug, help wanted
