### ISSUE TITLE
Set time (day in the week & time) when the app is automatically on or off 

### ISSUE THREAD

**Issue by thirdjean** [hovancik/stretchly#613] opened 2020-06-25 18:19 UTC
### Prerequisites

- [v] I'm using latest version: v0.21.1
- [v] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description
I'd like to recommend the function to set the time when the app is set to be on and off, based on time and on day in the week.
For example, that it automatically turns on from Monday to Friday, between 9:00 AM to 04:00 PM, and then is automatically off the rest of the time.

**Comment by hovancik** [comment] 2020-07-04 10:37
closing as duplicate of #342, please subscribe there for updates.

**Closed by hovancik** 2020-07-04 10:37 UTC
Labels: enhancement
