### ISSUE TITLE
[Feature request]: Let this application can only work in part of the time in a day.

### ISSUE THREAD

**Issue by DingChiLin** [hovancik/stretchly#1024] opened 2021-09-08 08:29 UTC
### Version

- [X] I'm using version 1.7.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### Problem description

I'm a big fan of this application. However, I have a meeting at morning every day, so I need to close this application so that I will not accidentally block my screen while sharing my presentation to others. The problem is that I usually forget to open it again for the rest of the day and it's not good for discipline.

### Possible solution

It will help a lot If I can choose the time in a day for this application to run. For example, let it only run from 10:00am to 11:00pm. Thank you!

### Alternative solutions

Nope

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2021-10-08 11:24
Hi, closing this as duplicate of #342 . 

Meanwhile, you could set up DND on Macos. Stretchly follows that.

**Closed as completed by hovancik** 2021-10-08 11:24 UTC

**Comment by DingChiLin** [comment] 2021-10-15 01:59
Thank You!
