### ISSUE TITLE
Break only active in one screen if user is using maximized windows

### ISSUE THREAD

**Issue by aleuca** [hovancik/stretchly#265] opened 2018-07-07 10:33 UTC
### Prerequisites

- [ ] I'm using latest version: v 

### Description

[Description of the issue]

Operating system: 

### Steps to Reproduce

1. Open a browser window and maximize it
2. force a break to start
3. 3-finger swipe to the desktop (right or left)

**Expected behavior:** Break reminder should always be on the screen even if user has swiped right or left to a different screen

**Actual behavior:** break reminder disappears if user swipes to a different screen

**Reproduces how often:** 100% observed

**Comment by hovancik** [comment] 2018-07-09 07:03
closing as duplicate of #256 

I guess we will never be able to 100% fix this but using `setKiosk` should help

**Closed by hovancik** 2018-07-09 07:03 UTC
