### ISSUE TITLE
Cmd+X does not skip the break anymore

### ISSUE THREAD

**Issue by casmarrav** [hovancik/stretchly#100] opened 2017-05-11 12:58 UTC
Ever since 0.8.1, where the break windows don't steal focus anymore (which I think is a big improvement), the shortcut for skipping doesn't work anymore.

**Comment by hovancik** [comment] 2017-05-11 13:04
What platform? It works on macOS fine for me. 

What has changed is, that before it could be 'Cmd+x' or 'Ctrl+x', but right now it's based on platform: 
mac is 'Cmd+x' only, windows, Linux is 'Ctrl+x', see [here](https://electron.atom.io/docs/api/global-shortcut/)

Maybe in your case some other program has that shortcut already? According to docs `When the accelerator is already taken by other applications, this call will still return false. This behavior is intended by operating systems, since they don’t want applications to fight for global shortcuts.`

**Comment by casmarrav** [comment] 2017-05-11 13:21
I'm using dvorak, does that make it different? It used to work in 0.8.0.
Of course, Cmd+X is Edit>Cut in many applications. If I can, I'll test with a program that does not have that command.

**Comment by hovancik** [comment] 2017-05-11 13:28
Before I was catching keyboard input from break window. Now (to prevent errors and have correct focus) I have to use global shortcus, as I can't catch keyboard input from break window anymore. 

I use eg. Atom editor, which has Cmd+x and works fine for me. I guess Atom's Cmd+X is not global, but local only. I have also tried with Dvorak and it works. 

As I have no focus on break window app, I have to use global shortcut. I guess I could add alternative shortcut...

**Comment by hovancik** [comment] 2017-05-11 13:29
Maybe you can try: quit stretchly and try `Cmd+X` if anything happens.

**Comment by hovancik** [comment] 2017-05-16 13:21
@casmarrav is it still an issue?

**Comment by casmarrav** [comment] 2017-05-16 15:23
Testing on Dvorak did you maybe use Cmd+Q?

**Comment by hovancik** [comment] 2017-05-16 15:26
Nope, `Cmd+Q` is not doing anything for me.

**Comment by hovancik** [comment] 2017-09-08 14:00
Could not reproduced, so closing.

**Closed by hovancik** 2017-09-08 14:00 UTC
