### ISSUE TITLE
Do not disturb mode stops working

### ISSUE THREAD

**Issue by fuzzy76** [hovancik/stretchly#413] opened 2019-06-13 07:21 UTC
After using my Mac for a while in Do Not Disturb mode (like in a long meeting) with occasionally the display going to sleep, go in and out of fullscreen apps, etc - Stretchly starts showing even when DnD mode is still on. The menubar menu says "On Do Not Disturb mode", but the breaks still appears. I am not 100% sure what triggers this, but it happens fairly often.

**Comment by hovancik** [comment] 2019-06-13 13:02
Ah well, I was afraid this would come one day 😃 It's rather complex thing.... 

I will try to reproduce.

**Comment by hovancik** [comment] 2019-06-13 13:04
One more thing: could you try to go to About, hit `Cmd/Ctrl+D` and paste here? Also, do you have any specific settings?

**Comment by fuzzy76** [comment] 2019-06-14 13:14
Oh man. That text was not possible to copy on Mac. :-/

```
breakPlanner: {reference: startMicrobreakNotification, timeleft: 3 minutes left, breakNumber: 2, postponesNumber: 0, Do Not Disturb: false}
settingsFile: /Users/hpe001/Librar/Application Support/stretchly/config.json
Node.js: 8.9.3, Chromium: 61.0.3163.100, Electron: 2.0.17
```

I don't remember what I chaned in the settings. I have 20 sec microbreaks every 10 miuntes, 3 minutes break every 5 microbreaks. Both can be postponed and skipped. On the misc page everything is on except silent notifications and monochrome tray icon.

Just realized you might want the about-debug-text from when it's misbehaving, which it wasn't now. I can repost next time it does.

**Comment by hovancik** [comment] 2019-06-14 13:38
Yeah when it happens ;] 

It's copy-able from linux but I'll check on mac when I am there

**Comment by hovancik** [comment] 2019-06-14 13:48
Ah, it's selectable but not copyable. Rather weird, I'll have to investigate.

**Comment by fuzzy76** [comment] 2019-06-18 07:33
Got it.
```
breakPlanner: {reference: startMicrobreakNotification, timeleft: 10 minutes left, breakNumber: 3, postponesNumber: 0, Do Not Disturb: true}
settingsFile: /Users/hpe001/Librar/Application Support/stretchly/config.json
Node.js: 8.9.3, Chromium: 61.0.3163.100, Electron: 2.0.17
```

**Comment by hovancik** [comment] 2019-07-15 18:44
@fuzzy76 is it still happening with new version? It has newer electron, v5. I was not able to replicate so far.

**Comment by fuzzy76** [comment] 2019-07-22 09:03
1. Stretchly triggers. I'm in a meeting.
2. I choose to postpone by clicking the bottom of the screen immediately.
3. I enable DnD using [SnoozeBar](https://github.com/banderson623/SnoozeBar) (which should not make a difference theoretically, but it does).
4. Info (Do Not Disturb is on at this point):
```
          breakPlanner: {reference: startMicrobreakNotification,
          timeleft: 10 minutes left,
          breakNumber: 1,
          postponesNumber: 0,
          Do Not Disturb: false}
          
          settingsFile: /Users/hpe001/Library/Application Support/stretchly/config.json
          Node.js: 12.0.0
          Chromium: 73.0.3683.121,
          Electron: 5.0.6
        ```
5. Stretchly triggers while DnD is on.

I tried reproduce with manually switching DnD, but could not on first try. Will try again.

**Comment by hovancik** [comment] 2019-07-22 10:29
Yeah you're right, with that app the dnd is not detected. I created issue here: https://github.com/banderson623/SnoozeBar/issues/2

**Comment by fuzzy76** [comment] 2019-09-03 11:14
I did get a break now:

```
          breakPlanner: {reference: startMicrobreakNotification,
          timeleft: 2 minutes left,
          breakNumber: 1,
          postponesNumber: 1,
          Do Not Disturb: true}
          
          settingsFile: /Users/hpe001/Library/Application Support/stretchly/config.json
          Node.js: 12.0.0
          Chromium: 73.0.3683.121,
          Electron: 5.0.6
        ```
I am at a conference. DnD is set manually on. The Mac has been in and out of hibernation a couple of times since I enabled DnD.

**Comment by hovancik** [comment] 2019-09-03 11:29
Just to be sure:  manually means without SnoozeBar?

**Comment by fuzzy76** [comment] 2019-09-03 11:35
Yes. And it just triggered again. Debug info still shows that dnd is detected.

**Comment by hovancik** [comment] 2022-12-23 14:08
Looks like SnoozeBar is not maintained anymore and there are new versions of macOS with different way for DND, so I am closing this.

**Closed by hovancik** 2022-12-23 14:08 UTC
