### ISSUE TITLE
[Feature request]: Schedule timeframe for breaks

### ISSUE THREAD

**Issue by cavazos-apps** [hovancik/stretchly#1229] opened 2022-11-09 15:23 UTC
### Version

- [X] I'm using version 1.12.0

### Existing requests

- [X] I've checked Existing requests

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 

### Problem description

It would be nice to be able to select a time frame in which breaks take place, working from home on my personal machine I would like to not have to start/stop the application any time I switch from work to personal time.

### Possible solution

Ability to select a time frame breaks can happen, i.e. 8 - 4, then outside of that window breaks do not happen. 

### Alternative solutions

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hovancik** [comment] 2022-12-19 12:57
duplicate of #342

**Closed as completed by hovancik** 2022-12-19 12:57 UTC
