### ISSUE TITLE
Dock stays hidden once coming back from a break

### ISSUE THREAD

**Issue by setek** [hovancik/stretchly#734] opened 2020-10-15 00:37 UTC
### Prerequisites

- [Y] I'm using latest version: v1.2.0 
- [Y] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [Y] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

When screen restores after break, dock does not restore visibility until user action.

Operating system: macOS  10.15.6

### Steps to Reproduce

1. Go on break
2. After returning from full screen break, Dock is not visible. Clicking on the screen or tapping any key will restore the dock visibility

**Expected behavior:** After returning from break, dock should restore its visibility settings

**Actual behavior:** Dock stays hidden until user action

**Reproduces how often:** 100% of the time

### Additional Information

This only seems to have started happening in the jump from 1.1.0 to 1.2.0, I think.

**Comment by hovancik** [comment] 2020-10-17 08:15
Hi @setek , are you sure you're on 1.2? 

If I understand your issue correctly, there was this issue in 1.1 (#690) but it was fixed in 1.2

**Comment by setek** [comment] 2020-10-17 08:26
Hi! Yes that's right, I went to Preferences > About and it says 1.2.0

**Comment by hovancik** [comment] 2020-10-17 11:18
Is this then the same issue as described at #690 or something else?

**Comment by setek** [comment] 2020-10-18 23:22
Hi, no this is something else, I don't get steps 5 and 6 happening with my issue.

What happens is, I come back from break, dock is not visible, active window says firefox, pressing keyboard renders the boop (you can't do anything sound) but if i tap touchpad to make firefox actually active, or i command tab to make firefox actually active, then the dock is visible again, and the real active window is firefox again.

**Comment by hovancik** [comment] 2020-10-24 09:24
Thanks @setek , I'll try to find a time to reproduce, I am bit overwhelmed these days ;/

**Comment by hovancik** [comment] 2020-10-25 10:11
Interestning, can't reproduce this, all seems to work fine here. Do you something special with dock? I am not macOS user so all my settings are defaults?

**Comment by setek** [comment] 2020-10-25 10:35
Nope, my dock is pretty standard. Always visible (not auto-hide) with magnification on, anchored to the bottom, pretty much usual settings 😄

**Comment by hovancik** [comment] 2020-10-25 10:49
Out of ideas, maybe try removing Stretchly and installing again? 

It is probably related somehow to this https://github.com/electron/electron/issues/25427 in some way I can't reproduce. 
There is PR to fix but no activity lately as it happens with Electron ;/ https://github.com/electron/electron/pull/25470

**Comment by setek** [comment] 2020-10-25 23:15
Ahh. I tried deleting and reinstalling, but it still happens. I don't suppose you have the previous releases up somewhere for download, do you? I don't think it happened on 1.1.0, so maybe I'll revert.

**Comment by hovancik** [comment] 2020-10-26 16:43
Yeah, here on Github you can find all previous version :) 

Anyways, that's the pain of working with electron, it brings new issues almost with every new version ;/

**Comment by setek** [comment] 2020-10-27 02:09
Oh. In the end, I'm having issues with 1.0.0 too, still hides the dock. Sigh

**Comment by hovancik** [comment] 2020-10-28 10:43
That's rather strange, not sure what could be the issue here. On mac I remember there being some app that could remove all files for app, might be worth doing that with Stretchly - only idea I have is that somehow broken electron version stays there somewhere between versions 1, 1.1 and 1.2; considering that this issue seems to be in 1.1 only for other people.

**Comment by setek** [comment] 2020-10-28 23:32
Okay I've gone into ~/Library/Application Support/ and have deleted the Stretchly directory, then uninstalled and reinstalled Stretchly 1.2.0. Have confirmed I lost my preferences, but when I skipped ahead to next break, the dock came back! Will continue to monitor throughout the day, but hopefully this is fine now!

**Comment by setek** [comment] 2020-11-01 22:38
Welp, it seemed to be fine all day, with many breaks.

Once I turned off my computer for the night, then back on again the next morning, it does the dock hiding thing again 😩

**Comment by setek** [comment] 2020-11-02 23:15
Figured it out! With the System Preferences > Users and Groups > Login Items > Stretchly
It was set to start on Login, but also set to Hide.
If I uncheck the Hide portion, the dock comes back when Stretchly comes back from a break.

**Comment by hovancik** [comment] 2020-11-03 18:53
Ou wow, that's so strange. Does it shows Stretchly icon in dock? In code, I am hiding it after start of the app and I wonder if that's somehow related.

**Comment by setek** [comment] 2020-11-06 05:22
Nope, no stretchly icon in dock :) and for the past few days, super stable. Do you want me to make a PR to this, just adding something to the readme or something, if you're experiencing issues like mine, to make sure the settings in startup on login?

**Comment by hovancik** [comment] 2020-11-07 15:44
Yes, that would be great. I think the best place is "Known Issues" in readme :)

**Closed** 2020-11-09 08:26 UTC

**Comment by haven2world** [comment] 2023-06-19 06:11
Thanks for all your discussion. Looks like it happens again on OS 13.4. And I found there was no "hide" checkbox in login items. Any idea about it?

**Comment by hovancik** [comment] 2023-06-20 12:38
@haven2world what Stretchly version are you on?

**Comment by haven2world** [comment] 2023-06-21 06:57
@hovancik 1.14.1.
