### ISSUE TITLE
1.0.0 segfaults on openSUSE

### ISSUE THREAD

**Issue by wpost** [hovancik/stretchly#633] opened 2020-07-21 03:09 UTC
Previous versions were solid as a rock on openSUSE 15.1 and 15.2, but new version 1.0.0 segfaults after a couple of hours. Despite trying to pay attention to what I was doing at the moment it goes down, I have been unable to determine what might be triggering this. Launching Stretchly from a terminal only tells me the terse "segmentation fault".

This isn't enough information to be useful, I know. I'd be happy to provide whatever else you need.

**Comment by hovancik** [comment] 2020-07-21 17:30
Hi and thanks for the report. 

I am not familiar with debugging on OS level, but seems that people recommend that running `gdb app-name` to get some more info. Can you try that?

**Comment by wpost** [comment] 2020-07-21 18:41
Will do!

**Comment by hovancik** [comment] 2020-07-25 17:34
Yeah, hard to tell if that would be helpful. 

Anyway it seems the problem is with Tray: `0x00007fffd5dbfcf1 in ?? () from /usr/lib64/libappindicator3.so.1` 

libappindicator3 is for tray stuff I believe. Thought in here there mention  `libappindicator1` https://www.electronjs.org/docs/api/tray

Maybe this is related https://github.com/electron/electron/issues/22652

**Comment by AlexeyDemidov** [comment] 2020-08-01 08:55
I have the same issue after update to version 1.0.0 under Linux Mint 19.3 - it segfaults every day

Jul 28 07:40:30 tahiti kernel: [108338.809306] stretchly[915]: segfault at 25a8ede82000 ip 00007f5e812ce951 sp 00007ffd6857d830 error 4 in libappindicator3.so.1.0.0[7f5e812c7000+c000]
Jul 28 22:06:58 kernel: [160328.649320] stretchly[16062]: segfault at 17ff50510000 ip 00007efec6b33951 sp 00007fffd81dd070 error 4 in libappindicator3.so.1.0.0[7efec6b2c000+c000]
Jul 29 12:19:56 kernel: [211507.276919] stretchly[19282]: segfault at 88531c47000 ip 00007f89c16f4951 sp 00007fffadc87140 error 4 in libappindicator3.so.1.0.0[7f89c16ed000+c000]
Jul 30 16:42:57 kernel: [313690.992280] stretchly[22809]: segfault at 3eb5a0353000 ip 00007fe34c3a0951 sp 00007ffca3b80260 error 4 in libappindicator3.so.1.0.0[7fe34c399000+c000]
Jul 31 12:50:29 kernel: [386144.495687] stretchly[27967]: segfault at 345e66780000 ip 00007fae14edf951 sp 00007fffbf0c20c0 error 4 in libappindicator3.so.1.0.0[7fae14ed8000+c000
Aug  1 02:51:39 kernel: [436615.391720] stretchly[17585]: segfault at 398cbe94a000 ip 00007f9318bc2951 sp 00007ffef24b4350 error 4 in libappindicator3.so.1.0.0[7f9318bbb000+c000]

See similar bugs in other Electron apps https://github.com/mattermost/desktop/issues/1235 https://github.com/flathub/com.discordapp.Discord/issues/30

**Comment by hovancik** [comment] 2020-08-08 08:37
Looks like bugs in libappindicator? TBH I am not sure if I understand what they are saying...

**Comment by lcnzg** [comment] 2020-08-09 01:33
Confirming the same issue on Linux Mint 18.2

**Comment by nicolae-stroncea** [comment] 2020-09-04 03:04
Can confirm Stretchly 1.0 also dies frequently(daily) after a couple of hours on Fedora 32

**Comment by nicolae-stroncea** [comment] 2020-09-05 16:35
Here's the gdb trace:
```
Thread 1 "stretchly" received signal SIGSEGV, Segmentation fault.
0x00007fffd6f2bb55 in status_icon_changes () from /lib64/libappindicator3.so.1
```

**Comment by hovancik** [comment] 2020-09-26 19:45
Hi folks, is still happening with 1.1?

**Comment by wpost** [comment] 2020-09-28 16:50
Yes it is, sadly. Symptoms and frequency seem to be the same as with 1.0. I'm still on openSUSE 15.2.

**Comment by AlexeyDemidov** [comment] 2020-09-29 16:14
Still the same issue

`Sep 29 18:28:24 kernel: [113375.827035] stretchly[5539]: segfault at 875dfbf2000 ip 00007f71da3e3951 sp 00007ffe1fca3a70 error 4 in libappindicator3.so.1.0.0[7f71da3dc000+c000]`

**Comment by gurpreetatwal** [comment] 2020-10-05 22:06
I noticed that this only happens for me if I run stretchy after I resume from a suspend. Are others seeing this before a suspend?

**Comment by wpost** [comment] 2020-10-05 23:21
I see this even though I do not suspend my computer.


--

Warren

________________________________

**Comment by mx781** [comment] 2020-10-26 08:29
A patch for the likely upstream bug in libappindicator has landed in the proposed repos for Ubuntu: https://bugs.launchpad.net/archlinux/+source/libappindicator/+bug/1867996

I [https://wiki.ubuntu.com/Testing/EnableProposed](added the proposed repo to my sources list), `apt update`d, ran `apt install libappindicator3-1` and installed stretchly from the .deb package from the Github Releases section (I had previously installed it via `snap` which bundles the dependencies in the snap volume, so that won't work and will probably need a re-bundling by the author/maintainers @hovancik - FYI). Haven't had stretchly segfault since :tada:

**Comment by hovancik** [comment] 2020-10-26 13:04
tanks for the update @mx781 :)  packages are built by `electron-builder` so no idea how they do it but I guess dependences will be corrected once fix lands in ubuntu, that's what's used on CI, I believe

**Comment by foundryspatial-duncan** [comment] 2021-01-13 04:13
I was getting segfaults from the snap version, so I uninstalled it and installed `libappindicator3-1` (but didn't add any special PPAs) and stretchly from the .deb pacakage. I'm still getting segfaults here, however. 

> [20308.867780] stretchly[3934]: segfault at 1f37d13b0000 ip 00007f3e4a222621 sp 00007ffdb147f1c0 error 4 in libappindicator3.so.1.0.0[7f3e4a21b000+c000]

If there's a known-good version of libappindicator, can that be bundled in the snap version, so that one would be stable? Or am I misunderstanding how snap images work?

**Comment by gurpreetatwal** [comment] 2021-01-13 16:34
> A patch for the likely upstream bug in libappindicator has landed in the proposed repos for Ubuntu: https://bugs.launchpad.net/archlinux/+source/libappindicator/+bug/1867996
> 
> I [added the proposed repo to my sources list](https://wiki.ubuntu.com/Testing/EnableProposed), `apt update`'d, ran `apt install libappindicator3-1` and installed stretchly from the .deb package from the Github Releases section (I had previously installed it via `snap` which bundles the dependencies in the snap volume, so that won't work and will probably need a re-bundling by the author/maintainers @hovancik - FYI). Haven't had stretchly segfault since tada

@mx781 could you put a comment on the bug thread on launchpad indicating that the fix worked for you? 

>The fix for this bug has been awaiting testing feedback in the -proposed repository for bionic for more than 90 days. Please test this fix and update the bug appropriately with the results. In the event that the fix for this bug is still not verified 15 days from now, the package will be removed from the -proposed repository.

https://bugs.launchpad.net/archlinux/+source/libappindicator/+bug/1867996/comments/18

**Comment by sandcore-dev** [comment] 2021-03-29 12:21
Stretchly regularly crashes for me too on Debian 10.8 (stable/buster). Current version is 1.4 and installed through Snap.

Just now it crashed during a break screen. Maybe the cause is that I took a bathroom break before the Stretchly break kicked in? Maybe the break screen code and the pause code (with tray icon change) interfere with each other or something?

**Comment by hovancik** [comment] 2021-03-29 12:38
@sandcore-dev can you show me the logs? `Preferences` -> `About` -> Hit `Ctrl+D` and logs file.

**Comment by sandcore-dev** [comment] 2021-03-29 13:48
Here's the output, with a grep on today's date. I should remark that this morning I thought Stretchly had not started automatically, but according to this log it had and crashed some time later. Timestamps are in GMT+2.

```
[2021-03-29 09:00:38.921] [info] Stretchly: loading settings
[2021-03-29 09:00:38.926] [info] Stretchly: starting Idle time monitoring
[2021-03-29 09:00:38.926] [info] Stretchly: starting DND monitoring
[2021-03-29 10:47:40.298] [info] Stretchly: loading settings
[2021-03-29 10:47:40.306] [info] Stretchly: starting Idle time monitoring
[2021-03-29 10:47:40.307] [info] Stretchly: starting DND monitoring
[2021-03-29 10:56:32.911] [info] Stretchly: skipping to Long Break
[2021-03-29 10:56:33.179] [info] Stretchly: showing window 1 of 1
[2021-03-29 10:56:33.180] [info] Stretchly: starting Mini Break
[2021-03-29 11:01:33.184] [info] Stretchly: finishing Long Break
[2021-03-29 11:02:28.441] [info] Stretchly: pausing breaks because of idle time
[2021-03-29 11:07:13.780] [info] Stretchly: resuming breaks after idle time
[2021-03-29 12:06:43.782] [info] Stretchly: showing Long Break notification
[2021-03-29 12:07:13.945] [info] Stretchly: showing window 1 of 1
[2021-03-29 12:07:13.946] [info] Stretchly: starting Mini Break
[2021-03-29 12:12:13.949] [info] Stretchly: finishing Long Break
[2021-03-29 12:12:18.324] [info] Stretchly: pausing breaks because of idle time
[2021-03-29 12:12:32.340] [info] Stretchly: resuming breaks after idle time
[2021-03-29 12:42:08.450] [info] Stretchly: pausing breaks because of idle time
[2021-03-29 13:00:32.793] [info] Stretchly: resuming breaks after idle time
[2021-03-29 14:00:02.793] [info] Stretchly: showing Long Break notification
[2021-03-29 14:00:33.106] [info] Stretchly: showing window 1 of 1
[2021-03-29 14:00:33.107] [info] Stretchly: starting Mini Break
[2021-03-29 14:00:34.314] [info] Stretchly: postponing Long Break
[2021-03-29 14:05:04.315] [info] Stretchly: showing Long Break notification
[2021-03-29 14:05:34.525] [info] Stretchly: showing window 1 of 1
[2021-03-29 14:05:34.526] [info] Stretchly: starting Mini Break
[2021-03-29 14:07:14.928] [info] Stretchly: loading settings
[2021-03-29 14:07:14.936] [info] Stretchly: starting Idle time monitoring
[2021-03-29 14:07:14.937] [info] Stretchly: starting DND monitoring
[2021-03-29 14:21:52.684] [info] Stretchly: loading settings
[2021-03-29 14:21:52.693] [info] Stretchly: starting Idle time monitoring
[2021-03-29 14:21:52.694] [info] Stretchly: starting DND monitoring
[2021-03-29 14:22:30.355] [info] Stretchly: skipping to Long Break
[2021-03-29 14:22:30.593] [info] Stretchly: showing window 1 of 1
[2021-03-29 14:22:30.594] [info] Stretchly: starting Mini Break
[2021-03-29 14:27:30.598] [info] Stretchly: finishing Long Break
[2021-03-29 15:27:00.600] [info] Stretchly: showing Long Break notification
[2021-03-29 15:27:30.762] [info] Stretchly: showing window 1 of 1
[2021-03-29 15:27:30.762] [info] Stretchly: starting Mini Break
[2021-03-29 15:27:32.574] [info] Stretchly: postponing Long Break
[2021-03-29 15:32:02.575] [info] Stretchly: showing Long Break notification
[2021-03-29 15:32:32.740] [info] Stretchly: showing window 1 of 1
[2021-03-29 15:32:32.741] [info] Stretchly: starting Mini Break
[2021-03-29 15:37:32.744] [info] Stretchly: finishing Long Break
```

**Comment by hovancik** [comment] 2021-03-29 14:12
@sandcore-dev is there no error message? When crash happens, there should be a message similar to this: 

```
[2021-03-15 15:41:34.952] [error] TypeError: Cannot read property 'rule' of undefined
    at new StatusMessages (/home/hovancik/workspace/hovancik/stretchly/app/utils/statusMessages.js:9:54)
    at updateToolTip (/home/hovancik/workspace/hovancik/stretchly/app/main.js:973:19)
    at updateTray (/home/hovancik/workspace/hovancik/stretchly/app/main.js:816:3)
    at App.createTrayIcon (/home/hovancik/workspace/hovancik/stretchly/app/main.js:233:3)
    at App.emit (events.js:327:22)
```

**Comment by sandcore-dev** [comment] 2021-03-29 16:41
Apparently not, I ran it on the commandline just now though:

```
18:36:04.666 › Stretchly: loading settings
18:36:04.676 › Stretchly: starting Idle time monitoring
18:36:04.676 › Stretchly: starting DND monitoring
(node:4261) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
/usr/share/libdrm/amdgpu.ids: No such file or directory
Segmentation fault
```
Only the first three lines show up in the log.

**Comment by hovancik** [comment] 2021-03-31 06:22
@sandcore-dev that's the issue with snap, as I read here: https://github.com/anbox/anbox/issues/1031#issuecomment-758830185

**Comment by hovancik** [comment] 2021-07-21 09:10
As this is issue with `libappindicator3`, I am closing this. Hopefully each OS will accept the fixed version soon.

**Closed by hovancik** 2021-07-21 09:10 UTC

**Comment by byarbrough** [comment] 2022-02-06 14:45
This might be starting to get some traction with electron https://github.com/electron/electron/issues/27527
