### ISSUE TITLE
Which released installer to use for Windows 10 (64-bit)? Both "Stretchly-Web-Setup-1.0.0.exe" and "Stretchly-Setup-1.0.0.exe" didn't work

### ISSUE THREAD

**Issue by thirdjean** [hovancik/stretchly#641] opened 2020-07-23 10:51 UTC
### Prerequisites

- [v] I'm using latest version: v 1.0.0
- [v] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [v] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

[Description of the issue]

Operating system: Windows 10 (64-bit)

Hello, I have maybe a beginner question. Which installer can I use to install Stretchly v1.0.0 onto my Windows 10 (64-bit) computer? I tried both of the following, but they didn't work:

(I previously had the v0.21.1 installed. I un-installed it in order to upgrade it to v1.0.0 as it didn't seem to have an internal update method?)

- "Stretchly-Web-Setup-1.0.0.exe": 
Installation was not able to be complete, I think during the process it was not able to install the uninstaller.exe for some reason. The files were installed into the Users\me\AppData\Roaming\stretchly folder. Without the uninstaller I cannot uninstall, and the Windows Control Panel marks this program as installed and cannot remove. Issue similar to #534.
I'll delete the folder manually that's in the AppData\Roaming\stretchly folder. Any tips to removing it from the list in the Control Panel is greatly appreciated.

- "Stretchly-Setup-1.0.0.exe"
Doesn't work as about 30% during installation the installer just says (Translated from Mandarin) "Installation stopped - Installation is not complete" on the screen, without aborting or anything. Just stands still with the progress not advancing.

Thanks for the help!

**Comment by hovancik** [comment] 2020-07-25 07:51
Hi @thirdjean , both installers are the right ones to install on Windows 10 64bit. Maybe try installing with administrator rights?

**Comment by hovancik** [comment] 2020-07-25 07:52
Btw there is no need to manually uninstall previous version, new installer uninstalls previous version by itself.

**Comment by thirdjean** [comment] 2020-07-26 10:28
Hi @hovancik, thanks for the response. Unfortunately nothing changes when I install with administrator rights. The installer stops at the point below, with the text saying (Translated from Mandarin) "Installation stopped - Installation is not complete." Situation doesn't change if I just install for myself or install for everyone on the same computer.

![image](https://user-images.githubusercontent.com/35175700/88476750-3c4e3580-cf3b-11ea-8b15-52212b7a22e8.png)

**Comment by thirdjean** [comment] 2020-07-27 08:31
Just wanting to add that now this happens as well when I try to install the older version of stretchly v0.21.1. 
I'm assuming that maybe something went wrong during the uninstallation.

![image](https://user-images.githubusercontent.com/35175700/88520719-3d8f6900-cff4-11ea-84fc-61e213b2e06d.png)

**Comment by hovancik** [comment] 2020-07-27 15:50
Looks like the problem is with not correctly uninstalled version of Stretchly v0.21.1, similar to the #636 . But to be honest, I don't know how to fix this. 

Which version do you see as installed in Control Panel ?

**Comment by thirdjean** [comment] 2020-07-27 16:00
Stretchly v1.0.0 is seen as installed in the Control Panel. Maybe the first installation left something wrong behind...

Could you tell me which one is the portable version on the Released page? I'd like to resort to that in the meantime to bypass the installation issue.

**Comment by hovancik** [comment] 2020-07-27 16:05
So 1.0.0. seems to be installed, but you can't run it? 

Potable version should be the file called `Stretchly-1.0.0-win.zip`

**Comment by thirdjean** [comment] 2020-07-27 16:09
Interestingly, the Stretchly v1.0.0 shortcut created by the installer points me to :
"C:\Program Files (x86)\Common Files\Wondershare\Wondershare Helper Compact\Wondershare Helper Compact.exe"
I recall searching about this Wondershare which is a malware that I still have to try to remove. Was this installation hijacked by this malware?

**Comment by hovancik** [comment] 2020-07-27 16:16
If you downloaded from Github, the files should not be infected. I am not even using real computer to build those installers, but virtual ones, so they should be clean. 

Do you have antivirus?

**Comment by JEVos** [comment] 2020-08-01 11:55
Having the same problem. My installation seemed to run and I just assumed it worked (no error message or anything). After installation I still got update pop-ups, so I checked the version number, which is still 0.21.1.

**Comment by hovancik** [comment] 2020-08-03 14:35
@JEVos can you try closing Stretchly and running it again? What version do you see in Installed apps?

**Comment by JEVos** [comment] 2020-08-03 14:39
> @JEVos can you try closing Stretchly and running it again? What version do you see in Installed apps?

Sure, in the app list it says 0.21.1 installed on 3/3/2020

**Comment by hovancik** [comment] 2020-08-05 18:01
I would try closing and then uninstalling all instances of Stretchly running and then try installing 1.0. The name of the app has changed from `stretchly` to `Stretchly` so it might be confusing the OS.

**Comment by JEVos** [comment] 2020-08-06 15:04
> I would try closing and then uninstalling all instances of Stretchly running and then try installing 1.0. The name of the app has changed from `stretchly` to `Stretchly` so it might be confusing the OS.

Thank you, that did the trick!

**Comment by hovancik** [comment] 2020-08-07 07:17
Awesome, glad to hear it worked :)

**Closed by hovancik** 2020-08-07 07:17 UTC
