### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by lclarke522** [hovancik/stretchly#457] opened 2019-08-23 14:36 UTC
### Prerequisites

- [x ] I'm using latest version: v0.20 
- [x ] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

I get `A JavaScript error occurred in the main process` error when launching Stretchly.

I thought it may be an issue with a custom config, so I deleted it and reinstated the default one. Still had an error.

I uninstalled Stretchly and reinstalled it. Still getting the error.

Operating system: Windows 10

### Steps to Reproduce

1. Launch Stretchly.

**Expected behavior:** Program will open up and start

**Actual behavior:** Errors (see attachments)

**Reproduces how often:** 100%

Thank you for your help!
![stretchly-error-01](https://user-images.githubusercontent.com/33603181/63600618-e7b77300-c591-11e9-8ec3-6db7d679f67e.png)
![stretchly-error-02](https://user-images.githubusercontent.com/33603181/63600619-e7b77300-c591-11e9-8c4d-211419627a3c.png)

**Comment by hovancik** [comment] 2019-08-28 05:42
Form the error it looks like something with settings. 

Did you close the app when deleting your custom config? Maybe paste your config here?

**Comment by dv0zn3r** [comment] 2019-10-02 22:37
Same issue on Mac. Same relevant steps to reproduce. Uninstall does not help. No custom config. The app just has stopped working.

**Comment by hovancik** [comment] 2019-10-03 06:01
@dv0zn3r what version of app do you use? can you copy the content of this file here? 

` /Users/USER/Library/Application Support/stretchly/config.json`

**Comment by dv0zn3r** [comment] 2019-10-03 06:49
@hovancik v0.20.1. I have just installed the app again. `stretchly` folder did not show up in `Application Support`. The error persists.

**Comment by hovancik** [comment] 2019-10-03 08:46
@dv0zn3r are you in correct folder? For me I can open the Library only from command line with `open /Users/USER/Library/`

If you are in correct one: do you have any antivirus or sth similar? Looks like stretchly can't create the folders and files it needs.

**Comment by hovancik** [comment] 2019-10-03 09:11
@dv0zn3r could also post screenshots of error? Or it's exactly the same? 

`utils/settings.js12:18` and error mentioned would suggest that stretchly did not successfully read the config file.

**Comment by dv0zn3r** [comment] 2019-10-03 09:15
@hovancik psa
![323213](https://user-images.githubusercontent.com/51778058/66114304-1150c900-e62b-11e9-834a-7aa116012b24.png)

**Comment by hovancik** [comment] 2019-10-04 16:43
lines of codes with errors

first screenshot
https://github.com/hovancik/stretchly/blob/v0.20.1/app/utils/settings.js#L12
https://github.com/hovancik/stretchly/blob/v0.20.1/app/main.js#L512

second screenshot
https://github.com/hovancik/stretchly/blob/v0.20.1/app/main.js#L263

no idea what could go wrong in this place, but it seems that settings were not loaded or are incorrect

**Comment by hovancik** [comment] 2019-10-04 16:44
@dv0zn3r if you paste your config file here https://jsoneditoronline.org/ is that without error?

**Comment by dv0zn3r** [comment] 2019-10-06 23:02
@hovancik No error. Finally, I have deleted everything in `/Users/USER/Library/Application Support/stretchly`. Then reinstalled the app. It works.

**Comment by hovancik** [comment] 2019-10-08 12:59
@dv0zn3r glad that helped! I must have been some other file then, not the settings file. Are you using any antivirus?

**Comment by hovancik** [comment] 2020-01-15 14:19
It's been few months, so I am closing this. Let me know if you still need help ;]

**Closed by hovancik** 2020-01-15 14:19 UTC
