### ISSUE TITLE
How to turn off the "Do not disturb" mode?

### ISSUE THREAD

**Issue by Bug-terminator** [hovancik/stretchly#827] opened 2020-12-29 08:51 UTC
RT.

**Comment by hovancik** [comment] 2020-12-29 08:58
Could you be more specific? Issue Template that you did not fill was there to help me understand your question.

**Comment by devProdigy** [comment] 2021-01-04 14:53
@Bug-terminator 
A friend of mine faced issue that in version 1.2 and 1.4 both (on Windows 10) was no way to go out from the "Do not disturb" mode by clicking on the "Resume.." or restarting the app. Even uninstalling didn't help.

So I offered to check "Show breaks even in Do Not Disturb mode" in preferences and it works now.
Don't know the details of this issue but this was a workaround :)

**Comment by hclimente** [comment] 2021-01-08 16:22
I encounter the same issue and solved it using the same workaround as @devProdigy

### Prerequisites

- [x] I'm using latest version: v1.4.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Stretchly remains in "Paused - Do Not Disturb is on" state, despite DND being off.

Operating system: macOS 11.1

### Steps to Reproduce

1. Open Stretchly
2. Make sure DND is off
3. Turn it on and off for good measure.

**Expected behavior:** Stretchly is active.

**Actual behavior:** Stretchly is paused.

**Reproduces how often:** 100%

### Additional Information

None.

### Debug information

Log after disabling the checkbox Show breaks even in Do Not Disturb mode:

> [2021-01-08 17:11:32.863] [info] Stretchly: starting DND monitoring
> [2021-01-08 17:11:32.863] [info] Stretchly: setting monitorDnd to true
> [2021-01-08 17:11:32.864] [info] Stretchly: saving settings file
> [2021-01-08 17:11:33.871] [info] Stretchly: pausing breaks for DND

**Comment by hovancik** [comment] 2021-01-09 12:01
Hi guys, 

for Windows, I noticed that users who upgrade from previous versions of Windows,  have always DND on for the library I use.  https://github.com/hovancik/stretchly#known-issues

Let me check on Mac... My guess is they changed something again and the library I use does not support it, yet. I am using https://github.com/felixrieseberg/electron-notification-state which then uses https://github.com/felixrieseberg/macos-notification-state for mac and https://github.com/felixrieseberg/windows-notification-state for windows

**Comment by hovancik** [comment] 2021-01-09 14:55
@hclimente just upgraded my macOS machine and can't reproduce, all seems fine for me

**Comment by hclimente** [comment] 2021-01-09 19:39
Thanks for checking. Digging in my settings, I found out that it was a problem with my configuration (DND was always on, regardless of what the icon in the control panel told me). I fixed it, and Stretchly worked as expected!

**Comment by hovancik** [comment] 2021-01-10 10:24
What was the issue? I remember some one person having issue with DND some time ago #413 that we never solved. I wonder if it might be related

**Comment by hclimente** [comment] 2021-01-10 10:38
What I did was to change the "From 00 to 00" in Notifications (System preferences) to something more reasonable (e.g. 19 to 00).

![Screenshot 2021-01-10 at 11 30 01](https://user-images.githubusercontent.com/5196281/104120439-30aec980-5337-11eb-9d19-eb79b156311d.png)

That did the trick yesterday. However, this morning Stretchly was still paused, and remained like that despite me checking and unchecking that box, and DND itself. Only restarting Stretchly solved the problem, so there might be a problem there after all? Here is the log, in case it's helpful:

> [2021-01-09 20:33:46.651] [info] Stretchly: resuming breaks for DND
> [2021-01-09 20:34:46.760] [info] Stretchly: pausing breaks for DND
> [2021-01-09 20:35:07.789] [info] Stretchly: resuming breaks for DND
> [2021-01-09 20:38:20.205] [info] Stretchly: pausing breaks for DND
> [2021-01-09 21:07:55.394] [info] System: suspend or lock
> [2021-01-09 21:07:55.395] [info] Stretchly: pausing breaks for 1
> [2021-01-09 21:19:56.833] [info] System: resume or unlock
> [2021-01-09 21:19:56.834] [info] Stretchly: not resuming breaks because in DND
> [2021-01-09 22:18:49.791] [info] System: suspend or lock
> [2021-01-09 22:19:19.531] [info] System: suspend or lock
> [2021-01-09 22:19:21.601] [info] System: resume or unlock
> [2021-01-09 22:19:35.262] [info] System: resume or unlock
> [2021-01-09 23:23:56.005] [info] System: suspend or lock
> [2021-01-09 23:23:56.384] [info] System: suspend or lock
> [2021-01-10 11:02:15.406] [info] System: resume or unlock
> [2021-01-10 11:02:22.112] [info] System: suspend or lock
> [2021-01-10 11:02:23.452] [info] System: resume or unlock
> [2021-01-10 11:02:37.992] [info] System: resume or unlock
> [2021-01-10 11:29:18.861] [info] Stretchly: loading settings
> [2021-01-10 11:29:18.866] [info] Stretchly: starting Idle time monitoring
> [2021-01-10 11:29:18.866] [info] Stretchly: starting DND monitoring
> [2021-01-10 11:29:37.922] [info] Stretchly: pausing breaks for DND
> [2021-01-10 11:35:09.824] [info] Stretchly: resuming breaks for DND

All the activity yesterday at ~20.30, same as today's activity at 11:30 is me playing with the DND settings.

**Comment by hovancik** [comment] 2021-01-12 15:12
A bit old thread, but might be that macOS has some weird bugs: https://www.reddit.com/r/MacOSBeta/comments/heqq4g/bug_anyone_else_not_getting_notifications_on_big/ , also https://www.reddit.com/r/MacOS/comments/kcvdn4/cannot_turn_off_the_do_not_disturb_on_big_sur_is/

**Comment by hovancik** [comment] 2021-01-12 15:44
So I tried to put DND for few minutes (via that shceduler in System Prefs) but all was good after I came back. Must be something else that is interfering, but not sure what it could be. I am not using macOS so have no experience with DND that I could add

**Comment by hclimente** [comment] 2021-01-13 14:26
Since that issue, everything has been working just fine. So yes, I guess it was another instance of Big Sur's faulty DND.

Thanks for your help and your time!

**Comment by hovancik** [comment] 2021-01-14 08:43
Ok, since original author did not clarify what they are after, I am closing this

**Closed by hovancik** 2021-01-14 08:43 UTC

**Comment by AminDar** [comment] 2023-02-19 18:05
I didn't want to open new issue but on Mac M1 OS13.1 the app doesn't work and shows " the DND is on" although it's not!
