### ISSUE TITLE
Does not show on all monitors

### ISSUE THREAD

**Issue by SaraCOlsson** [hovancik/stretchly#490] opened 2019-10-23 13:50 UTC
### Prerequisites

- [x ] I'm using latest version: v 
- [ x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)

### Description

The break screen does not showon all monitors. I have tried uninstalling and installing again and changing the settings in different combinations but nothing works.

I installed 0.21.0.exe on windows 10.

It used ti work before but hasn’t worked in some time now.   

Operating system: 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hustakm** [comment] 2019-10-24 15:56
I has to same issue.
Autor do you have any suggestion?
I finding that the same problem had some user 1 year ago.

**Comment by hovancik** [comment] 2019-10-24 16:14
Hey guys sorry to hear that. I don't windows OS but I will try to create some virtual machine to test it out.

**Comment by qmch** [comment] 2019-11-13 23:23
I'm having a similar issue on Windows 10. For mine, the break screen shows up on a second monitor but it is incorrectly scaled and not centered. The scaling was correct in the previous version, and this occurs for all breaks.

![image](https://user-images.githubusercontent.com/16869820/68813008-5bb16680-0629-11ea-9185-a203a3bc9b75.png)

**Comment by hovancik** [comment] 2019-11-19 12:21
@qmch do you remember which version it was working?

**Comment by qmch** [comment] 2019-11-20 04:23
@hovancik it was working on the previous version, v0.20.1. I've just downloaded that version to check and the scaling is correct in that version on both monitors.

**Comment by omer-g** [comment] 2019-12-04 13:37
Hello, I'm using v0.21.0 and have "breaks are shown on all monitors" selected, but I don't see the message on my external monitor (extended mode). I'm running Windows 10. Thanks

**Comment by hovancik** [comment] 2019-12-17 08:07
hey folks, are you on latest Windows? I can't reproduce this ;[ (in Virtualbox, though, which might make difference). I had user with different issue that was solved with Windows upgrade

![image](https://user-images.githubusercontent.com/4745859/70976570-76558000-20ac-11ea-9147-16faddfadfd6.png)

Also, what settings do you have? Maybe my settings are wrong? 

![image](https://user-images.githubusercontent.com/4745859/70976468-473f0e80-20ac-11ea-9e20-8650b846c89f.png)

**Comment by omer-g** [comment] 2019-12-17 11:01
Hey, what is your windows version? it seems your settings are fine. I have Windows 1909 and Windows Update asks for no newer updates.

**Comment by hovancik** [comment] 2019-12-17 11:07
my version is the same as yours, 1909

**Comment by qmch** [comment] 2020-01-02 18:10
I have 200% scaling on because my laptop is a Surface Pro (2017), maybe that's the issue? Works fine on 0.20.1.

![image](https://user-images.githubusercontent.com/16869820/71683626-ebc97d80-2d47-11ea-8868-6b419fd84ce5.png)

**Comment by Yekmaz** [comment] 2020-01-11 13:32
In my Case, When Choose "Full screen" this problem occurs

**Comment by m-kremer** [comment] 2020-02-28 09:47
I am experiencing the same issue, and can confirm Yekmaz' comment. It only occurs when 'Full screen' option is turned on.

**Comment by yo1995** [comment] 2020-04-20 04:08
Also experiencing this issue with latest version for both Stretchly and Windows 10.

When the scale of my 2 monitors are not the same, Stretchly display correctly on the 250% scaled screen, whereas being too large on the 100% scaled screen.

**Comment by ozish-au** [comment] 2020-04-27 01:45
Confirming that the issue occurs only when "full screen" is selected. Windows 8.1.

**Comment by XuShenLZ** [comment] 2020-07-20 17:21
Version 1.0.0 still has this issue. It does not show on all monitors in full-screen mode. Works well in "window" mode. I really look forward to this fix

[OS: Win 10 Version 2004, Build 19041.388]

**Comment by hovancik** [comment] 2020-07-21 17:37
@XuShenLZ is this with specific apps or something like that? 

I don't have a Windows OS machine, but with this settings everything works fine for me with Virtual Box: 

<img width="531" alt="image" src="https://user-images.githubusercontent.com/4745859/88087553-6691a300-cb89-11ea-9217-ce541d0cd7ac.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/4745859/88087658-87f28f00-cb89-11ea-89a4-b606fc4981bf.png">

**Comment by XuShenLZ** [comment] 2020-07-22 00:20
> @XuShenLZ is this with specific apps or something like that?
> 
> I don't have a Windows OS machine, but with this settings everything works fine for me with Virtual Box:
> 
> <img alt="image" width="531" src="https://user-images.githubusercontent.com/4745859/88087553-6691a300-cb89-11ea-9217-ce541d0cd7ac.png">
> 
> <img alt="image" width="919" src="https://user-images.githubusercontent.com/4745859/88087658-87f28f00-cb89-11ea-89a4-b606fc4981bf.png">

@hovancik Thanks for the reply! It worked today magically... It may because of a system reboot. Bravo! Great app and appreciate your work!

**Comment by XuShenLZ** [comment] 2020-07-23 18:56
> @hovancik Thanks for the reply! It worked today magically... It may because of a system reboot. Bravo! Great app and appreciate your work!

Reproduced the problem. So it is not because of the reboot. It worked when I do not have windows open on the second monitor. Otherwise it will be hidden underneath. No matter whether the window there is active or not. It is reported in #639 too.

**Comment by hovancik** [comment] 2020-07-25 17:41
Ah, gotcha. I will close this one, as this was about not getting anything at all, and let's talk about that issue there. The issue is then "Window now shown on top of other apps on seconds screen"

**Closed by hovancik** 2020-07-25 17:41 UTC
