### ISSUE TITLE
New inverted monochrome menubar icon not white

### ISSUE THREAD

**Issue by csemken** [hovancik/stretchly#736] opened 2020-10-15 07:42 UTC
### Prerequisites

- [x] I'm using latest version: v1.2.0 
- [x] I've checked [Known issues](https://github.com/hovancik/stretchly#known-issues)
- [x] I've checked [Open issues](https://github.com/hovancik/stretchly/issues)

### Description

Since the logo change, the inverted monochrome menubar icon is no longer white and thus does not match the system design (at least in Gnome 3 and Windows 10 dark theme).  Here are the old and new icons for both systems:

OS | Old icon (white) | New icon (grey)
------------ | ------------ | -------------
Ubuntu | ![stretchly_icon_old_lin](https://user-images.githubusercontent.com/39151322/96018080-1c982080-0e4b-11eb-9ae3-8a83efdf2b74.png) | ![strechly_icon_new_lin](https://user-images.githubusercontent.com/39151322/96018098-21f56b00-0e4b-11eb-9497-3550993b3af0.png)
Windows | ![strechly_icon_old_win](https://user-images.githubusercontent.com/39151322/96018046-10ac5e80-0e4b-11eb-97cd-c403af440e2f.png) | ![strechly_icon_new_win](https://user-images.githubusercontent.com/39151322/96018058-15711280-0e4b-11eb-8c20-1fbab0a8f498.png)

Operating system: Ubuntu 20.04 and Windows 10

### Steps to Reproduce

1. Install stretchly
2. Change settings: “Theme” → “Menubar icon” to “Monochrome” and tick “Inverted Monochrome”
3. (On Windows: change to dark theme)

**Expected behavior:** white icon that “blends in” with system icons (like before)

**Actual behavior:** grey icon, distinct from system icons

**Reproduces how often:** always

**Comment by hovancik** [comment] 2020-10-17 10:54
Hi @csemken and thanks for feedback, but I don't plan to change that.

**Comment by hovancik** [comment] 2020-10-18 18:22
Actually, I'll keep this opened for a while and see what other people think.

**Comment by csemken** [comment] 2020-10-18 18:28
Thanks, I appreciate it.  Any particular reason why you were not planning to change this?  If it is about the extra work, would you accept a PR that makes `graphics/appicon-mono-dark-mode{,paused}.svg` white?

**Comment by hovancik** [comment] 2020-10-19 17:35
Hi @csemken , 
it was done by designer and I like it ;) But other reasons as well: 

- in my experience with these things is once I change it, people start asking to bring it back. It's hard to please everybody and not every OS has same colors. 
- I never really liked the white one pre 1.0, seems to be a bit off
- so it looks to me that it should not be white, but white-ish, if changed. I would like to do some research how different OSes/Distros/Apps deal with such a theme. Then we also need to look at dark one. MacOS is changing color automagically (from dark to light), so I'll try to check how it looks there once I have a chance. 

So yeah, if we can get some data, I am willing to change my mind :)

**Comment by hovancik** [comment] 2024-12-28 13:04
Hi, I will close this as not likely to happen.

**Closed** 2024-12-28 13:08 UTC
Labels: enhancement
