### ISSUE TITLE
[Bug]: No texts on Break windows

### ISSUE THREAD

**Issue by KarlManong** [hovancik/stretchly#1048] opened 2021-11-25 01:31 UTC
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

monterey 12.0.1 apple m1

### Reproduction steps

1. just take a mini break
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time

### Expected Behavior

![image](https://user-images.githubusercontent.com/2627662/143343118-ab1378fa-e769-4fc5-9e64-794f72c40b2f.png)

### Actual Behavior

same to https://github.com/hovancik/stretchly/issues/1043

![image](https://user-images.githubusercontent.com/2627662/143343489-ddd28b8a-e6df-4fb5-9789-81e0fb7cf429.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raphaeltao** [comment] 2021-11-25 01:39
same on 14“ M1 pro  MacBook Pro 2021 Monterey 12.0.1 version 1.8.1

**Comment by vardecab** [comment] 2021-11-25 14:11
Same on Intel, Monterey 12.0.1.

**Comment by hovancik** [comment] 2021-11-25 15:54
Works fine for me on old-school macbook pro, not sure how to reproduce. Anything in logs or elsewhere?

**Comment by johe123qwe** [comment] 2021-11-25 16:53
Same on 2015 Macbook pro, macos Catalina 10.15.7.
Where can I see the log?

**Comment by hovancik** [comment] 2021-11-25 19:14
https://github.com/hovancik/stretchly#debugging

**Comment by borna761** [comment] 2021-11-25 21:34
I'm having the same issue. I don't know if this helps, but I have found that when forcing a break (ie Skip to the next --> Mini Break), it starts off with the white page for a second or two, but then switches to the proper background.

See video (I had to record it with my phone as I couldn't reproduce it when doing screen recording):
https://user-images.githubusercontent.com/9056534/143501482-87c9be89-7740-4cc2-8bc3-67e374e4ec41.mov

However, when it pops up on its regular schedule, it still has the same problem.

**Comment by richardstevenhack** [comment] 2021-11-26 02:57
Possibly relevant to this: just upgraded to the latest release on openSUSE Leap 15.3 and instead of getting the white window I get a fully black window. It's better than the white window because at least I can see the time bar and the postpone/skip button more easily. I can live with that since I don't care about the text displays.

**Comment by JorisDebonnet** [comment] 2021-11-26 10:34
For me, on Windows 10, 1.8.1. works fine most of the time, but "sometimes" I also get the completely white screen (3 times so far I think, in the past few days). The logs doesn't say anything interesting:
```
[2021-11-26 11:28:36.944] [info]  Stretchly: showing Long Break notification
[2021-11-26 11:29:09.494] [info]  Stretchly: showing window 1 of 1
[2021-11-26 11:29:09.495] [info]  Stretchly: starting Long Break  ==> this one was white
[2021-11-26 11:30:06.183] [info]  Stretchly: reseting breaks
```

Note: it looks different than with the issue in 1.8.0. That time, it was white text on almost-white background, so you could still just see the text. This time, I can't see anything, and I can't find anywhere to click to make it go away, which I why I use the tray icon to "reset breaks".

**Comment by JorisDebonnet** [comment] 2021-11-26 10:35
For what it's worth, here's the screenshot on Windows 10 from when it happened just now.

![Screenshot 2021-11-26 113507](https://user-images.githubusercontent.com/3286264/143567472-768bfd0d-d9d3-4ca1-a3c8-9978b92ef742.png)

**Comment by vortexnix** [comment] 2021-11-27 10:12
Same issue on Kubuntu 20.04. The white screen is seen only some of the times (completely random seemingly). Whenever it occurs, it occurs only for the Long Break and never for Short break.

**Comment by hovancik** [comment] 2021-11-27 17:33
That sucks, it never seems to happen to me. Not sure how to reproduce this..

**Comment by drb01** [comment] 2021-11-29 12:15
FWIW I get the impression the white window problem happens pretty reliably on the first break message after waking the PC from sleep. I'm using Win 10 Pro.

**Comment by vortexnix** [comment] 2021-11-29 15:02
I tested @drb01 theory and was able to reproduce the issue in Kubuntu 20.04
Kill stretchly in terminal:
`pkill stretchly`
Start stretchly:
`stretchly`
The first break will be shown in white.

**Comment by jkocot** [comment] 2021-12-01 16:41
I get this error really reliably ;) The white screen is not entirely white (the letters are scarcely visible), but I get it with every break. On Win10 Pro. I can't see anything unusual in the logs (the ones pointed by the About screen), is there anything more I can check to somehow trace this?

EDIT: Sorry, forget my comment. I had the 1.8.0 version installed. I had to have used the old installer I had on my computer instead of the just downloaded one - I was sure I was installing 1.8.1. With 1.8.1 the first breaks showed fine (proper color).

**Comment by mike-crawfurd** [comment] 2021-12-02 08:34
Same behavior here on Windows, does not matter if it is an upgrade or a new installation, the pause screens are blank. Any information we can provide to help with the investigation of this?

**Comment by svaneke** [comment] 2021-12-02 11:12
Similar issue on macOS 10.14 with Stretchly 1.8.1. Though the page doesn’t stay white, it _flashes_ white before showing the correct screen and colour.

**Comment by BriannaLoveless** [comment] 2021-12-06 19:09
Same issue for me. Stretchly 1.8.1 on windows. Stays white the entire time and cannot see words nor timer progress. I reset to default settings and it seemed to work for the next few breaks then got the white screen again. Affected both mini and long breaks for me

**Comment by zmruivo** [comment] 2021-12-07 11:15
Same issue. Version 1.8.1 on windows.

**Comment by JorisDebonnet** [comment] 2021-12-07 19:31
Can someone change the title so it's doesn't specify macos anymore? Since it (sometimes) appears on Windows and Kubuntu too. 

It is not a color issue: it's just that nothing is being rendered on the window apart from that empty progress bar in the center. I verified this by double clicking everywhere from top to bottom. There isn't anything there.

I imagine perhaps some functionality being executed in the wrong order sometimes, due to asynchronous functions? Something not properly waiting for something else to be 'ready'?

**Comment by richardstevenhack** [comment] 2021-12-07 21:26
> It is not a color issue: it's just that nothing is being rendered on the window apart from that empty progress bar in the center. I verified this by double clicking everywhere from top to bottom. There isn't anything there.
> 

Correcting my previous post In my case on openSUSE 15.3, apparently the "show exercise tips" message preference was reset when I upgraded the system. Apparently the theme was changed to Graphite Crystal which is where the black window came from. Once I changed the exercise tips preference back, my Stretchly is working correctly now. All messages show. So I think we can remove openSUSE Leap 15.3 from the list of systems affected.

**Comment by hovancik** [comment] 2021-12-11 18:28
Hi, just changed the title. My feeling is that when I ask for break data when break starts, they are not received. But as on both my mac and Linux I can't reproduce this, can't really say :( I think it's probably related either to hardware or some specific state of the OS (high cpu or something). In past there were for example weird issue with people with specific graphic card.

**Comment by xeruf** [comment] 2021-12-18 18:08
Same issue on my Arch Linux, but not on all devices weirdly enough :/

**Comment by Jake331** [comment] 2021-12-20 22:58
Here because same thing's happening to me probably 3 out of 4 breaks. (Sometimes it works.) MacOS Big Sur, 2017 MacBook Air.

**Comment by hovancik** [comment] 2021-12-22 08:38
Hi all, can anyone try running this PR locally? #1073 I've added some debugging. Here is example: 

```
2021-12-22 09:30:54.150] [info]  Stretchly: skipping to Mini Break
[2021-12-22 09:30:55.297] [info]  Stretchly: showing window 1 of 1
[2021-12-22 09:30:55.306] [info]  Stretchly: starting Mini Break
[2021-12-22 09:30:55.296] [debug] Mini Break window: asking for break data
[2021-12-22 09:30:55.342] [debug] Main: Sending Mini Break data
[2021-12-22 09:30:55.390] [debug] Mini Break windows: break data received
[2021-12-22 09:30:56.293] [debug] Main: Removing listener for sending Mini Break data
[2021-12-22 09:31:25.309] [info]  Stretchly: finishing Mini Break
[2021-12-22 09:31:48.576] [info]  Stretchly: skipping to Long Break
[2021-12-22 09:31:50.086] [info]  Stretchly: showing window 1 of 1
[2021-12-22 09:31:50.092] [info]  Stretchly: starting Long Break
[2021-12-22 09:31:50.097] [debug] Long Break window: asking for break data
[2021-12-22 09:31:50.173] [debug] Main: Sending Long Break data
[2021-12-22 09:31:50.220] [debug] Long Break windows: break data received
[2021-12-22 09:31:50.884] [debug] Main: Removing listener for sending Long Break data
[2021-12-22 09:34:15.280] [info]  Stretchly: finishing Long Break
```

Seeing that now, maybe the issue is that in some cases I remove listener too early, but would like to see what the added logs say when there is an issue.

**Comment by robpomeroy** [comment] 2021-12-22 09:30
@hovancik - I'm not sure where to download this PR's Windows exe, but I'm happy to test, if you can supply a link.

**Comment by mhuijzer** [comment] 2021-12-22 09:59
> Hi all, can anyone try running this PR locally? #1073 I've added some debugging. Here is example:

Running the latest version (branch _debug/break-window_) this is what I get (the 'suspend or lock' is because I need to lock and unlock my user account in order to get the frozen Stretchly screen to disappear):
```
10:55:34.266 > Stretchly: initializing...
10:55:34.307 > Stretchly: loading preferences
10:55:34.338 > Stretchly: starting Idle time monitoring
10:55:34.341 > Stretchly: starting Do Not Disturb monitoring
10:55:35.906 > Stretchly: checking for new version (local: v1.8.1, remote: 1.8.1)
[20436:1222/105535.913:INFO:CONSOLE(0)] "10:55:35.906 ÔÇ║ Stretchly: checking for new version (local: v1.8.1, remote: 1.8.1)", source:  (0)
10:55:45.725 > Stretchly: skipping to Mini Break
[20436:1222/105545.872:INFO:CONSOLE(0)] "10:55:45.725 ÔÇ║ Stretchly: skipping to Mini Break", source:  (0)
10:55:47.885 > Main: Removing listener for sending Mini Break data
[20436:1222/105547.897:INFO:CONSOLE(0)] "10:55:47.885 ÔÇ║ Main: Removing listener for sending Mini Break data", source:  (0)
[20436:1222/105548.316:INFO:CONSOLE(0)] "10:55:47.885 ÔÇ║ Main: Removing listener for sending Mini Break data", source:  (0)
10:55:48.357 > Mini Break window: asking for break data
[20436:1222/105548.395:INFO:CONSOLE(0)] "10:55:47.885 ÔÇ║ Main: Removing listener for sending Mini Break data", source:  (0)
10:55:48.395 > Mini Break window: asking for break data
10:55:48.471 > Stretchly: showing window 1 of 2
10:55:48.474 > Stretchly: starting Mini Break
[20436:1222/105548.482:INFO:CONSOLE(0)] "10:55:48.357 ÔÇ║ Mini Break window: asking for break data", source:  (0)
[20436:1222/105548.493:INFO:CONSOLE(0)] "10:55:48.395 ÔÇ║ Mini Break window: asking for break data", source:  (0)
[20436:1222/105548.497:INFO:CONSOLE(0)] "10:55:48.471 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)        
[20436:1222/105548.504:INFO:CONSOLE(0)] "10:55:48.471 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)
[20436:1222/105548.526:INFO:CONSOLE(0)] "10:55:48.474 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
[20436:1222/105548.529:INFO:CONSOLE(0)] "10:55:48.474 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
10:55:48.535 > Stretchly: showing window 2 of 2
[20436:1222/105548.541:INFO:CONSOLE(0)] "10:55:48.471 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)
[20436:1222/105548.548:INFO:CONSOLE(0)] "10:55:48.474 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
[20436:1222/105548.567:INFO:CONSOLE(0)] "10:55:48.535 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
[20436:1222/105548.573:INFO:CONSOLE(0)] "10:55:48.535 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
[20436:1222/105548.574:INFO:CONSOLE(0)] "10:55:48.535 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
10:55:52.028 > System: suspend or lock
10:55:52.044 > Stretchly: finishing Mini Break
10:55:52.069 > Stretchly: pausing breaks for 1
[20436:1222/105552.099:INFO:CONSOLE(0)] "10:55:52.028 ÔÇ║ System: suspend or lock", source:  (0)
[20436:1222/105552.115:INFO:CONSOLE(0)] "10:55:52.044 ÔÇ║ Stretchly: finishing Mini Break", source:  (0)
[20436:1222/105552.116:INFO:CONSOLE(0)] "10:55:52.069 ÔÇ║ Stretchly: pausing breaks for 1", source:  (0)
10:55:54.945 > System: resume or unlock
10:55:54.963 > Stretchly: resuming breaks
[20436:1222/105555.047:INFO:CONSOLE(0)] "10:55:54.945 ÔÇ║ System: resume or unlock", source:  (0)
[20436:1222/105555.068:INFO:CONSOLE(0)] "10:55:54.963 ÔÇ║ Stretchly: resuming breaks", source:  (0)
[12520:1222/105736.386:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
```

**Comment by hovancik** [comment] 2021-12-22 10:37
@robpomeroy there is no exe, it's just for running from source :( 
@mhuijzer thanks for the test! I guess I was right: 

```
10:55:47.885 > Main: Removing listener for sending Mini Break data
10:55:48.357 > Mini Break window: asking for break data
```

can you try pulling the updated branch and see what happens? I've tried to do some fixing

**Comment by robpomeroy** [comment] 2021-12-22 10:40
> @robpomeroy there is no exe, it's just for running from source :( @mhuijzer thanks for the test! I guess I was right:

Ah, okay. I'll try that. 🙂

**Comment by hovancik** [comment] 2021-12-22 10:42
@robpomeroy unless you have NodeJS running locally, I think it's better wait  for others to try :) it's not that simple to set everything up

**Comment by robpomeroy** [comment] 2021-12-22 10:48
> @robpomeroy unless you have NodeJS running locally, I think it's better wait for others to try :) it's not that simple to set everything up

I do. I dabble with some React development. 🙂👍 I'm running `npm install` at the moment.

**Comment by robpomeroy** [comment] 2021-12-22 10:52
With the debug/break-window branch, running the Electron app, I am not seeing the bug.

Is something going wrong with the build process perhaps?

EDIT: I see you made some fixes. I'm at 320ae2c3dca570ffc8590928700ab3160fb25cd0.

**Comment by robpomeroy** [comment] 2021-12-22 10:57
I DO see the bug on trunk though.

**Comment by mhuijzer** [comment] 2021-12-22 11:05
> @robpomeroy there is no exe, it's just for running from source :( @mhuijzer thanks for the test! I guess I was right:
> 
> ```
> 10:55:47.885 > Main: Removing listener for sending Mini Break data
> 10:55:48.357 > Mini Break window: asking for break data
> ```
> 
> can you try pulling the updated branch and see what happens? I've tried to do some fixing

No problem! I did. The break window seems to work normal? At least: it has information on it, there is a countdown happening and it listens to the color settings. However, it now throws a 'system can't find a file' error during execution. 

Besides that, when the break was finished it took some time (I would say a few seconds) for the break window to close again. I can't remember that from earlier versions, but maybe that is my faulty memory.

Anyway: this is the log:
```
12:01:51.458 > Stretchly: initializing...
12:01:51.492 > Stretchly: loading preferences
12:01:51.527 > Stretchly: starting Idle time monitoring
12:01:51.532 > Stretchly: starting Do Not Disturb monitoring
[1222/120151.683:ERROR:registration_protocol_win.cc(106)] CreateFile: Het systeem kan het opgegeven bestand niet vinden. (0x2)
[1222/120151.726:ERROR:registration_protocol_win.cc(106)] CreateFile: Het systeem kan het opgegeven bestand niet vinden. (0x2)
12:01:53.226 > Stretchly: checking for new version (local: v1.8.1, remote: 1.8.1)
[8236:1222/120153.231:INFO:CONSOLE(0)] "12:01:53.226 ÔÇ║ Stretchly: checking for new version (local: v1.8.1, remote: 1.8.1)", source:  (0)
12:01:57.338 > Stretchly: skipping to Mini Break
[8236:1222/120157.487:INFO:CONSOLE(0)] "12:01:57.338 ÔÇ║ Stretchly: skipping to Mini Break", source:  (0)
[1222/120159.460:ERROR:registration_protocol_win.cc(106)] CreateFile: Het systeem kan het opgegeven bestand niet vinden. (0x2)
[1222/120159.479:ERROR:registration_protocol_win.cc(106)] CreateFile: Het systeem kan het opgegeven bestand niet vinden. (0x2)
12:01:59.893 > Stretchly: showing window 2 of 2
12:01:59.913 > Stretchly: showing window 1 of 2
12:01:59.921 > Stretchly: starting Mini Break
[8236:1222/120159.935:INFO:CONSOLE(0)] "12:01:59.893 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
[8236:1222/120159.935:INFO:CONSOLE(0)] "12:01:59.893 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
[8236:1222/120159.948:INFO:CONSOLE(0)] "12:01:59.913 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)
[8236:1222/120159.953:INFO:CONSOLE(0)] "12:01:59.921 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
12:01:59.940 > Mini Break window: asking for break data
12:01:59.976 > Main: Sending Mini Break data
12:01:59.982 > Main: Sending Mini Break data
[8236:1222/120159.985:INFO:CONSOLE(0)] "12:01:59.976 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120159.986:INFO:CONSOLE(0)] "12:01:59.982 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.004:INFO:CONSOLE(0)] "12:01:59.893 ÔÇ║ Stretchly: showing window 2 of 2", source:  (0)
[8236:1222/120200.006:INFO:CONSOLE(0)] "12:01:59.913 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)
[8236:1222/120200.007:INFO:CONSOLE(0)] "12:01:59.921 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
[8236:1222/120200.007:INFO:CONSOLE(0)] "12:01:59.976 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.007:INFO:CONSOLE(0)] "12:01:59.982 ÔÇ║ Main: Sending Mini Break data", source:  (0)
12:02:00.014 > Mini Break window: asking for break data
12:02:00.024 > Main: Sending Mini Break data
12:02:00.028 > Main: Sending Mini Break data
[8236:1222/120200.036:INFO:CONSOLE(0)] "12:02:00.024 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.039:INFO:CONSOLE(0)] "12:02:00.028 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.141:INFO:CONSOLE(0)] "12:01:59.913 ÔÇ║ Stretchly: showing window 1 of 2", source:  (0)
[8236:1222/120200.142:INFO:CONSOLE(0)] "12:01:59.940 ÔÇ║ Mini Break window: asking for break data", source:  (0)
[8236:1222/120200.153:INFO:CONSOLE(0)] "12:02:00.014 ÔÇ║ Mini Break window: asking for break data", source:  (0)
12:02:00.159 > Mini Break windows: break data received
12:02:00.168 > Mini Break windows: break data received
[8236:1222/120200.206:INFO:CONSOLE(0)] "12:02:00.024 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.206:INFO:CONSOLE(0)] "12:02:00.159 ÔÇ║ Mini Break windows: break data received", source:  (0)
[8236:1222/120200.206:INFO:CONSOLE(0)] "12:02:00.028 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.267:INFO:CONSOLE(0)] "12:01:59.921 ÔÇ║ Stretchly: starting Mini Break", source:  (0)
[8236:1222/120200.268:INFO:CONSOLE(0)] "12:01:59.976 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.279:INFO:CONSOLE(0)] "12:02:00.168 ÔÇ║ Mini Break windows: break data received", source:  (0)
[8236:1222/120200.281:INFO:CONSOLE(0)] "12:01:59.982 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.286:INFO:CONSOLE(0)] "12:02:00.024 ÔÇ║ Main: Sending Mini Break data", source:  (0)
[8236:1222/120200.290:INFO:CONSOLE(0)] "12:02:00.028 ÔÇ║ Main: Sending Mini Break data", source:  (0)
12:02:19.927 > Main: Removing listener for sending Mini Break data
12:02:19.937 > Stretchly: finishing Mini Break
[8236:1222/120219.994:INFO:CONSOLE(0)] "12:02:19.927 ÔÇ║ Main: Removing listener for sending Mini Break data", source:  (0)
[8236:1222/120220.009:INFO:CONSOLE(0)] "12:02:19.927 ÔÇ║ Main: Removing listener for sending Mini Break data", source:  (0)
[8236:1222/120220.019:INFO:CONSOLE(0)] "12:02:19.937 ÔÇ║ Stretchly: finishing Mini Break", source:  (0)
[1222/120353.446:ERROR:registration_protocol_win.cc(106)] CreateFile: Het systeem kan het opgegeven bestand niet vinden. (0x2)
[10304:1222/120354.172:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
```

**Comment by hovancik** [comment] 2021-12-22 12:17
@robpomeroy thanks for  the confirmation
@mhuijzer I also did update Electron, looks like the electron issue: https://github.com/electron/electron/issues/32133 

I'll try to think of another way to remove listeners, I guess the delay with closing is because I am removing listeners before closing windows

**Comment by mhuijzer** [comment] 2021-12-22 12:24
Thanks for the quick fix! 

> @mhuijzer I also did update Electron, looks like the electron issue: https://github.com/electron/electron/issues/32133 

That sounds plausible indeed. 

> I'll try to think of another way to remove listeners, I guess the delay with closing is because I am removing listeners before closing windows

Sounds good!

**Comment by hovancik** [comment] 2021-12-22 17:09
I've improved the code a bit, but probably "slow" closing is unrelated to this change. Can anyone test again? I would close this issue :)

**Comment by robpomeroy** [comment] 2021-12-22 18:29
> I've improved the code a bit, but probably "slow" closing is unrelated to this change. Can anyone test again? I would close this issue :)

Happy to test, but would be tomorrow now.

**Comment by robpomeroy** [comment] 2021-12-23 08:07
@hovancik It's working well for me Jan, but you're right - the slow closing (circa 2.5 seconds) is still there.

**Comment by hovancik** [comment] 2021-12-23 08:35
Thanks! It's also because I am not showing "0 seconds remaining", I think, so there is "1 second" for 2 second; I think.

**Closed as completed** 2021-12-23 08:39 UTC
Labels: bug, help wanted

**Comment by KarlManong** [comment] 2021-12-27 06:19
This problem is gone, Thank you! I really appreciate it!

**Comment by vortexnix** [comment] 2021-12-27 06:21
Rectified in Kubuntu 20.04 as well. Sincere Thanks.
