### ISSUE TITLE
[Bug]:  app Exclusions not working on v 1.10.0 in MacOS Catalina

### ISSUE THREAD

**Issue by imyellan** [hovancik/stretchly#1105] opened 2022-02-28 21:41 UTC
### Version

- [X] I'm using version 1.9.0

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### Reproduction steps

1. Upgrade to Stretchly 1.10.0
2. Close Stretchly
3. Add application to the appExclusions section of the config.json file (in my case, Zoom or Keynote), with `"rule": "pause"`, and `"active": true`.
4. Reopen Stretchly
5. Open one of these applications

Can confirm that the issue seems to be with v1.10.0, since appExclusion pausing works after reverting back to v1.9.0.
...
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of time

### Expected Behavior

Expect Stretchly to pause while application is open.

### Actual Behavior

Stretchly does not pause, but continues to run on schedule while the application is open.

### Relevant log output

```shell
## In v1.9.0:
[2022-02-28 16:23:30.740] [info]  Stretchly: initializing...
[2022-02-28 16:23:30.771] [info]  Stretchly: loading preferences
[2022-02-28 16:23:30.795] [info]  Stretchly: starting Idle time monitoring
[2022-02-28 16:23:30.797] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-28 16:23:30.798] [info]  Stretchly: starting App exclusions monitoring
[2022-02-28 16:23:32.103] [info]  Stretchly: pausing breaks as 'pause' exclusion found running: 'zoom.us'

## In v1.10.0:
2022-02-26 13:00:55.890] [info]  Stretchly: initializing...
[2022-02-26 13:00:55.906] [info]  Stretchly: loading preferences
[2022-02-26 13:00:55.935] [info]  Stretchly: starting Idle time monitoring
[2022-02-26 13:00:55.937] [info]  Stretchly: starting Do Not Disturb monitoring
[2022-02-26 13:00:55.938] [info]  Stretchly: starting App exclusions monitoring
```

### Preferences

```shell
{
	"microbreakDuration": 25000,
	"microbreakInterval": 1500000,
	"breakDuration": 300000,
	"breakInterval": 2,
	"breakNotification": true,
	"microbreakNotification": true,
	"breakNotificationInterval": 30000,
	"microbreakNotificationInterval": 10000,
	"microbreak": true,
	"break": true,
	"microbreakStrictMode": false,
	"breakStrictMode": false,
	"morningHour": 8,
	"microbreakPostpone": true,
	"breakPostpone": true,
	"microbreakPostponeTime": 120000,
	"breakPostponeTime": 300000,
	"microbreakPostponesLimit": 1,
	"microbreakPostponableDurationPercent": 30,
	"breakPostponesLimit": 1,
	"breakPostponableDurationPercent": 30,
	"mainColor": "#567890",
	"transparentMode": false,
	"opacity": 0.9,
	"audio": "crystal-glass",
	"volume": 1,
	"fullscreen": true,
	"ideas": true,
	"naturalBreaks": true,
	"naturalBreaksInactivityResetTime": 300000,
	"allScreens": true,
	"useIdeasFromSettings": false,
	"language": "en",
	"notifyNewVersion": true,
	"isFirstRun": false,
	"posLatitude": 0,
	"posLongitude": 0,
	"useMonochromeTrayIcon": true,
	"useMonochromeInvertedTrayIcon": false,
	"silentNotifications": true,
	"monitorDnd": true,
	"microbreakStartSoundPlaying": false,
	"breakStartSoundPlaying": false,
	"themeSource": "system",
	"endBreakShortcut": "CmdOrCtrl+X",
	"breakWindowWidth": 0.85,
	"breakWindowHeight": 0.85,
	"checkNewVersion": true,
	"breakIdeas": [
		{
			"data": [
				"Not alone",
				"Do you find it hard to take a break alone? Try to do it with a co-worker. Aside from making it easier to stick to breaks, you will have a chance to get to know them better. Taking breaks together increases productivity."
			],
			"enabled": true
		},
		{
			"data": [
				"Step away",
				"Do you ever notice how your brain can figure things out by itself? All it takes is to step away from the computer and take a break to think about something totally unrelated."
			],
			"enabled": true
		},
		{
			"data": [
				"Microbreaks",
				"Rest is a key component in ensuring the performance of the musculoskeletal system. Frequent breaks can decrease the duration of a task and help lower the exposure to ergonomic injury risk."
			],
			"enabled": true
		},
		{
			"data": [
				"Meditation",
				"Research studies suggest that mindfulness-based exercises help decrease anxiety, depression, stress, and pain, and help improve general health, mental health, and quality of life. Not sure how to start? There are numerous apps to help you out."
			],
			"enabled": true
		},
		{
			"data": [
				"Blink",
				"Looking at screens for a long time causes you to blink less, thus exposing your eyes to the air. Blink rapidly for a few seconds to refresh the tear film and clear dust from the eye surface."
			],
			"enabled": true
		},
		{
			"data": [
				"Ergonomics",
				"Improper height and angle of the keyboard, mouse, monitor or working surface can cause health problems. Take some time to read about desk ergonomics."
			],
			"enabled": true
		},
		{
			"data": [
				"Move",
				"There are a lot of ways you can exercise within your office. Try marching in place or doing desk push-ups."
			],
			"enabled": true
		},
		{
			"data": [
				"Change",
				"Do you have a stability ball or standing work desk? Consider replacing your desk chair with them for a while."
			],
			"enabled": true
		},
		{
			"data": [
				"Notice",
				"Are you daydreaming or having trouble focusing? It is a sign that you need to take a break."
			],
			"enabled": true
		},
		{
			"data": [
				"Tech",
				"How about taking a no-tech walk?"
			],
			"enabled": true
		},
		{
			"data": [
				"Metabolism",
				"Emerging research shows that sitting for long periods of time contributes to risk of metabolic syndrome, heart attack and stroke risk and overall death risk, among others. Taking regular walking breaks can help your circulation, working to counteract some of those problems."
			],
			"enabled": true
		},
		{
			"data": [
				"Active Meetings",
				"How about moving meetings from the conference room to the concourse? Walking not only burns calories but it may even foster a sense of collaboration."
			],
			"enabled": true
		},
		{
			"data": [
				"Fruit",
				"Take your time and eat some fruit. Slowly. Notice the flavor, the texture, the freshness."
			],
			"enabled": true
		},
		{
			"data": [
				"Bathrooms",
				"Walk to the farthest bathroom in the worksite facility when going to the restroom."
			],
			"enabled": true
		},
		{
			"data": [
				"Coffee break",
				"Going on coffee break? Consider doing a 5-minute walk every time you go for one."
			],
			"enabled": true
		},
		{
			"data": [
				"Colleagues",
				"Do not email or message office colleagues, walk to their desks to communicate with them."
			],
			"enabled": true
		},
		{
			"data": [
				"Learning",
				"In a study of healthy volunteers, NIH researchers found that taking short breaks, early and often, may help our brains learn new skills."
			],
			"enabled": true
		},
		{
			"data": [
				"Exercise",
				"Evidence suggests small amounts of regular exercise can bring dramatic health benefits, including measurably reducing stress."
			],
			"enabled": true
		},
		{
			"data": [
				"Repeat",
				"Have you found your stretch-ly-routine? Do not forget to repeat it for more than once to better fight effects of prolonged sitting."
			],
			"enabled": true
		},
		{
			"data": [
				"Wrist and forearm",
				"Extend your arms with the palms facing towards you, then slowly rotate the hands four times clockwise, then four times counter-clockwise."
			],
			"enabled": true
		},
		{
			"data": [
				"Back stretching",
				"Join your hands behind your head, then lift them together up above your head ending with your palms facing upward."
			],
			"enabled": true
		},
		{
			"data": [
				"Mobilize",
				"For every thirty minutes of stagnation, you should have at least one minute of stimulation."
			],
			"enabled": true
		},
		{
			"data": [
				"7 Minute Workout",
				"This workout packs in a full-body exercise routine in a fraction of the time. But as with any exercise, be careful. There are numerous apps to get you started."
			],
			"enabled": true
		},
		{
			"data": [
				"Pulse",
				" Raise your pulse rate to 120 beats per minute for 20 straight minutes four or five times a week doing anything you enjoy. Regularly raising your heart rate results in improved cardiovascular health."
			],
			"enabled": true
		},
		{
			"data": [
				"Take the stairs ",
				"Studies have shown that stair climbing, which is considered vigorous-intensity physical activity, burns more calories per minute than jogging."
			],
			"enabled": true
		},
		{
			"data": [
				"Make art",
				"Art therapy is known to have great mental health benefits, especially when it comes to stress management. How about writing a quick poem, taking a picture or painting something small?"
			],
			"enabled": true
		},
		{
			"data": [
				"Declutter",
				"A clean space helps your focus at work and is often linked to positive emotions like happiness."
			],
			"enabled": true
		},
		{
			"data": [
				"Lunch outside",
				"Nature is linked to positive emotions and decreased stress and anxiety. Whenever possible, try to take your daily lunch break outside, surrounded by some greenery."
			],
			"enabled": true
		},
		{
			"data": [
				"Public transport",
				"If you use public transport regularly, you can stand instead of sitting. If it is possible, try to replace as many of your daily trips as possible with walking or cycling."
			],
			"enabled": true
		},
		{
			"data": [
				"Yawning",
				"Yawning can be really helpful, as it produces tears to help moisten and lubricate the eyes."
			],
			"enabled": true
		},
		{
			"data": [
				"Focus change",
				"Hold one finger close to the eye and focus on it. Slowly move the finger away, focus far into the distance and then back to the finger. Bring the finger back and focus on something far away."
			],
			"enabled": true
		},
		{
			"data": [
				"Palming",
				"While seated, brace elbows on the desk and close to the desk edge. Let your weight fall forward and cup hands over eyes. Close your eyes and inhale slowly through nose and hold for few seconds. Continue deep breathing."
			],
			"enabled": true
		},
		{
			"data": [
				"Hand squeezes",
				"Squeeze a pair of balled-up socks or a soft rubber ball, hold for 5 seconds. Repeat whole process few times."
			],
			"enabled": true
		}
	],
	"microbreakIdeas": [
		{
			"data": "Go grab a glass of water.",
			"enabled": true
		},
		{
			"data": "Slowly look all the way left, then right.",
			"enabled": true
		},
		{
			"data": "Slowly look all the way up, then down.",
			"enabled": true
		},
		{
			"data": "Close your eyes and take few deep breaths.",
			"enabled": true
		},
		{
			"data": "Close your eyes and relax.",
			"enabled": true
		},
		{
			"data": "Stretch your legs.",
			"enabled": true
		},
		{
			"data": "Stretch your arms.",
			"enabled": true
		},
		{
			"data": "Is your sitting posture correct?",
			"enabled": true
		},
		{
			"data": "Slowly turn head to side and hold for 10 seconds.",
			"enabled": true
		},
		{
			"data": "Slowly tilt head to side and hold for 5-10 seconds.",
			"enabled": true
		},
		{
			"data": "Stand from your chair and stretch.",
			"enabled": true
		},
		{
			"data": "Refocus your eyes on an object at least 20 meters away.",
			"enabled": true
		},
		{
			"data": "Take a moment to think about something you appreciate.",
			"enabled": true
		},
		{
			"data": "Take a moment to smile at being alive.",
			"enabled": true
		},
		{
			"data": "A truly ergonomic workstation is one that you regularly push away from.",
			"enabled": true
		},
		{
			"data": "Close your eyes and count your breaths.",
			"enabled": true
		},
		{
			"data": "Close your eyes and name the things you hear.",
			"enabled": true
		},
		{
			"data": "Place your fingertips on your shoulders. Roll your shoulders forward for 10 seconds, then backward.",
			"enabled": true
		},
		{
			"data": "Raise your right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on the other side.",
			"enabled": true
		},
		{
			"data": "With your right hand, grab each finger of your left hand in turn and squeeze. Repeat on the other side.",
			"enabled": true
		},
		{
			"data": "Stand up and do a lunge. Hold for 10 seconds, then do the other leg.",
			"enabled": true
		},
		{
			"data": "Close your eyes and simply notice whatever arises in current moment, without judgement.",
			"enabled": true
		},
		{
			"data": "Focus every 20 minutes for 20 seconds on an object at 20 feet distance.",
			"enabled": true
		},
		{
			"data": "If you need help, ask for it.",
			"enabled": true
		},
		{
			"data": "Do one thing at a time.",
			"enabled": true
		},
		{
			"data": "Is your attention spent wisely?",
			"enabled": true
		},
		{
			"data": "Change your sitting posture.",
			"enabled": true
		},
		{
			"data": "Expose your eyes to natural light.",
			"enabled": true
		},
		{
			"data": "With your eyes closed, slowly and gently raise your eyes to the ceiling and back down to the floor.",
			"enabled": true
		},
		{
			"data": "With your eyes closed, slowly and gently move your eyes to the left, then slowly to the right.",
			"enabled": true
		},
		{
			"data": "Shake your hands out to get some relief.",
			"enabled": true
		},
		{
			"data": "One at a time, touch the tip of each finger to the tip of your thumb so they make an O-shape.",
			"enabled": true
		},
		{
			"data": "Make a fist and then slide your fingers up until they point toward the ceiling, like you're telling someone to stop.",
			"enabled": true
		},
		{
			"data": "Make a fist and then fan your fingers out and stretch them as far as you can.",
			"enabled": true
		}
	],
	"showBreaksAsRegularWindows": false,
	"appExclusions": [
		{
			"rule": "pause",
			"active": true,
			"commands": [
				"zoom.us",
				"Keynote"
			]
		}
	],
	"appExclusionsCheckInterval": 1000,
	"pauseForSuspendOrLock": true,
	"pauseBreaksShortcut": "",
	"resumeBreaksShortcut": "",
	"screen": "primary",
	"timeToBreakInTray": false,
	"currentTimeInBreaks": false
}
```

### Additional information

```shell
Can confirm that the issue seems to be with v1.10.0, since appExclusion pausing works after reverting back to v1.9.0.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fbnrst** [comment] 2022-03-01 08:06
I'm on version v1.10.0, and I seem to have a similar issue with one difference: For me, Stretchly always stays in paused mode. So, when I turn of "Do not disturb" Stretchly still shows "Paused - Do not disturb is on".

**Comment by hovancik** [comment] 2022-03-05 09:10
Interesting, all seems to work fine for me in 1.10. I've also tried running with your config and all works as expected for me.

Sorry, but not sure what to try ;/

**Comment by Cheprer** [comment] 2022-03-15 12:04
Since I'm having a same issue here is the log from Mac Console app, hope you will find something relevant:
```
default	12:50:35.994899+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Stretchly.app/Contents/, NSFilePath=/Applications/Stretchly.app/Contents/PlugIns, NSUnderlyingError=0x139853250 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	12:50:35.995054+0100	lsd	- 45683955: Checking whether application is managed at file:///Applications/Stretchly.app//net.hovancik.stretchly
default	12:50:36.008080+0100	lsd	net.hovancik.stretchly:5:5:1:1:Building bundle record for app
default	12:50:36.008337+0100	lsd	net.hovancik.stretchly:5:5:2:1:Built bundle record for app
default	12:50:36.025007+0100	lsd	net.hovancik.stretchly:5:4:2:1:_LSServerRegisterItemInfo result = 0
default	12:50:36.029762+0100	runningboardd	Launch request for app<application.net.hovancik.stretchly.14721323.14721326(501)> is using uid 501 (divined from auid 501 euid 501)
default	12:50:36.029822+0100	runningboardd	Acquiring assertion targeting app<application.net.hovancik.stretchly.14721323.14721326(501)> from originator [daemon<com.apple.Finder(501)>:523] with description <RBSAssertionDescriptor| "LS launch net.hovancik.stretchly" ID:369-523-34448 target:app<application.net.hovancik.stretchly.14721323.14721326(501)> attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LaunchRoleBackground" sourceEnvironment:"(null)">
	]>
default	12:50:36.029880+0100	runningboardd	Assertion 369-523-34448 (target:app<application.net.hovancik.stretchly.14721323.14721326(501)>) will be created as active
default	12:50:36.030109+0100	runningboardd	Executing launch request for app<application.net.hovancik.stretchly.14721323.14721326(501)> (LS launch net.hovancik.stretchly)
default	12:50:36.030148+0100	runningboardd	Creating and launching job for: app<application.net.hovancik.stretchly.14721323.14721326(501)>
default	12:50:36.030164+0100	runningboardd	_mutateContextIfNeeded called for net.hovancik.stretchly
default	12:50:36.061132+0100	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    CFBundleDisplayName = Stretchly;
    bundleIDs =     (
        "net.hovancik.stretchly"
    );
    isPlaceholder = 0;
}
default	12:50:36.091319+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] This process will not be managed.
default	12:50:36.091337+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] HOME is <private>
default	12:50:36.091351+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] TMPDIR is <private>
default	12:50:36.091367+0100	runningboardd	Now tracking process: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:36.091445+0100	runningboardd	Using default underlying assertion for app: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:36.091475+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: running-active (role: Background)
default	12:50:36.091526+0100	runningboardd	Acquiring assertion targeting [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] from originator [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] with description <RBSAssertionDescriptor| "RB Underlying Assertion" ID:369-369-34449 target:23186 attributes:[
	<RBSDomainAttribute| domain:"com.apple.underlying" name:"defaultUnderlyingAppAssertion" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
default	12:50:36.091814+0100	runningboardd	Assertion 369-369-34449 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) will be created as active
default	12:50:36.092027+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] reported to RB as running
default	12:50:36.093519+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring jetsam update because this process is not memory-managed
default	12:50:36.093554+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring suspend because this process is not lifecycle managed
default	12:50:36.093594+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Set darwin role to: Background
default	12:50:36.093228+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: running-active (role: Background)
default	12:50:36.093636+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring GPU update because this process is not GPU managed
default	12:50:36.094547+0100	runningboardd	Acquiring assertion targeting [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] from originator [daemon<com.apple.coreservices.launchservicesd>:327] with description <RBSAssertionDescriptor| "backgroundApp:23186" ID:369-327-34450 target:23186 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleNonUserInteractive" sourceEnvironment:"(null)">
	]>
default	12:50:36.094614+0100	runningboardd	Assertion 369-327-34450 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) will be created as active
default	12:50:36.097513+0100	runningboardd	Acquiring assertion targeting [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] from originator [daemon<com.apple.coreservices.launchservicesd>:327] with description <RBSAssertionDescriptor| "backgroundApp:23186" ID:369-327-34451 target:23186 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleNonUserInteractive" sourceEnvironment:"(null)">
	]>
default	12:50:36.097548+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: running-active (role: NonUserInteractive)
default	12:50:36.097568+0100	runningboardd	Assertion 369-327-34451 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) will be created as active
default	12:50:36.099122+0100	runningboardd	Invalidating assertion 369-327-34450 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) from originator [daemon<com.apple.coreservices.launchservicesd>:327]
default	12:50:36.099685+0100	runningboardd	Acquiring assertion targeting [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] from originator [daemon<com.apple.coreservices.launchservicesd>:327] with description <RBSAssertionDescriptor| "backgroundApp:23186" ID:369-327-34452 target:23186 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleNonUserInteractive" sourceEnvironment:"(null)">
	]>
default	12:50:36.099838+0100	runningboardd	Assertion 369-327-34452 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) will be created as active
default	12:50:36.100765+0100	runningboardd	Invalidating assertion 369-327-34451 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) from originator [daemon<com.apple.coreservices.launchservicesd>:327]
default	12:50:36.101603+0100	runningboardd	Invalidating assertion 369-523-34448 (target:app<application.net.hovancik.stretchly.14721323.14721326(501)>) from originator [daemon<com.apple.Finder(501)>:523]
default	12:50:36.102468+0100	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Stretchly
default	12:50:36.102269+0100	runningboardd	Acquiring assertion targeting [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] from originator [daemon<com.apple.coreservices.appleevents(55)>:475] with description <RBSAssertionDescriptor| "AE/Stretchly" ID:369-475-34453 target:23186 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	12:50:36.102432+0100	runningboardd	Assertion 369-475-34453 (target:[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]) will be created as active
default	12:50:36.103954+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: running-active (role: UserInteractiveNonFocal)
default	12:50:36.105041+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring jetsam update because this process is not memory-managed
default	12:50:36.105055+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring suspend because this process is not lifecycle managed
default	12:50:36.105072+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Set darwin role to: NonUserInteractive
default	12:50:36.105088+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring GPU update because this process is not GPU managed
default	12:50:36.105185+0100	runningboardd	Successfully acquired underlying assertion for [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:36.105458+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring jetsam update because this process is not memory-managed
default	12:50:36.105691+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring suspend because this process is not lifecycle managed
default	12:50:36.105736+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Set darwin role to: UserInteractiveNonFocal
default	12:50:36.105772+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring GPU update because this process is not GPU managed
default	12:50:36.218010+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring jetsam update because this process is not memory-managed
default	12:50:36.218022+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: running-active (role: UserInteractiveNonFocal)
default	12:50:36.218029+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring suspend because this process is not lifecycle managed
default	12:50:36.218081+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] Ignoring GPU update because this process is not GPU managed
default	12:50:38.935771+0100	kernel	ASP: Security policy would not allow process: 23186, /Applications/Stretchly.app/Contents/MacOS/Stretchly
default	12:50:38.937458+0100	runningboardd	[app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186] termination reported by launchd (9, 8, 9)
default	12:50:38.937478+0100	runningboardd	Removing process: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:38.938113+0100	runningboardd	Removing launch job for: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:38.938759+0100	runningboardd	Removed job for [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:38.938792+0100	runningboardd	Removing assertions for terminated process: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:38.955782+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: none (role: None)
default	12:50:38.956537+0100	runningboardd	Calculated state for app<application.net.hovancik.stretchly.14721323.14721326(501)>: none (role: None)
default	12:50:38.957740+0100	launchservicesd	Hit the server for a process handle c9117c300005a92 that resolved to: [app<application.net.hovancik.stretchly.14721323.14721326(501)>:23186]
default	12:50:38.960737+0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Stretchly, _appTrackingState = 2
```

**Comment by davidllorente** [comment] 2022-07-20 14:16
I've also had this same issue with 1.10 and after downgrading to 1.09 the appExclusions feature works correctly. I have MacOS Mojave 10.14.6.

In addition, I suffered a weird bug with the system's ReportCrash process constantly using up a lot of CPU while Stretchly 1.10 was running, so my guess is that something was constantly crashing. While being closed it stopped doing it, and with 1.09 all is working correctly.

**Comment by hovancik** [comment] 2022-07-24 09:27
Sorry, but I am unable to reproduce :( 

In 1.10 I added app exclusion check interval so you could try making it bigger, this check consumes a lot of power. 

It could also be some weird electron bug, so maybe when I upgrade it, it will be better.

**Comment by Cheprer** [comment] 2022-08-14 19:42
Hey, small update just installed latest 1.11.0 and it works alright on Macbook M1 Pro. Using brew with these commands:
```
brew update && brew upgrade --cask
brew reinstall --cask --no-quarantine stretchly
```

Maybe can be put just to upgrade stretchly with param --no-quarantine

**Comment by imyellan** [comment] 2022-08-15 14:14
@Cheprer thanks for the heads up, I just upgraded to 1.11.0 as well and app exclusion are working again for me.

**Comment by hovancik** [comment] 2022-08-16 11:13
Great, I'll close this, then.

**Closed as completed by hovancik** 2022-08-16 11:13 UTC
