### ISSUE TITLE
[Bug]:   White/Grey screen on Windows 10 and 11 

### ISSUE THREAD

**Issue by mike-crawfurd** [hovancik/stretchly#1067] opened 2021-12-09 09:53 UTC
### Version

- [X] I'm using version 1.8.1

### Known issues

- [X] I've checked Known issues

### Existing issues

- [X] I've checked Existing issues

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2 and Windows 11

### Reproduction steps

1. Start mini break
2.
3.
...
First time after upgrade the screen renders fine, after that it fails every time.

### Expected Behavior

Normal Mini Break screen with hints and tips

### Actual Behavior

Grey/Write screen, no text, no progress bar, CtrlX does work

![image](https://user-images.githubusercontent.com/24622847/145373903-af91e026-4b16-435f-8920-131b182c90fd.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mike-crawfurd** [comment] 2021-12-09 09:56
Sorry, wrong screenshot

![image](https://user-images.githubusercontent.com/24622847/145374494-1f0f097c-64db-4f35-b353-8e0c98893861.png)

**Comment by KarlBishop** [comment] 2021-12-09 20:19
I have the same issue since updating to 1.8 / 1.8.1 on my Windows 10 laptop.

My issue isn't consistent though: I was getting the grey screen every time on 1.8 but since upgrading to 1.8.1 I only see it now and again. And when I have a second monitor connected, I sometimes get the grey screen on one monitor and the normal screen on the other.

**Comment by jnpwly** [comment] 2021-12-09 22:13
Seeing the same issue -- that is, the grey screen with a darker grey line only.
Windows 10, Stretchly 1.8.1.

**Comment by SaeedBaig** [comment] 2021-12-09 23:40
Same issue here (Windows 10, Stretchly 1.8.1), but it's inconsistent; sometimes my Stretchly reminder will show up as a blank screen with just a time bar like in mike-crawfurd's screenshot (only grey), and sometimes it works fine (and what's weird is that I'm using the "Green Clouds" theme, but the reminder window is still grey).
<img width="816" alt="bug" src="https://user-images.githubusercontent.com/29703429/145494838-4482ae5b-dc59-4761-8c3f-8f8f95c2e069.png">

I think this might be a Windows-specific problem; I have Stretchly 1.81 on Linux as well (Kubuntu 20.04) and it doesn't have this bug.

**Comment by mcanyucel** [comment] 2021-12-10 07:01
Same issue, started few days ago on windows 11 Stretchly 1.8.1.  Force reinstall (using choco) did not work.

**Comment by mcanyucel** [comment] 2021-12-10 11:53
Ok did a little bit more digging and found out that if you have ```Controlled Folder Access``` enabled in Ransomware Protection of Windows security, you get the blank screen. If you disable it, then you get the correct functionality. If you disable then enable it, you get the first break warning fine but the rest results in empty windows. Maybe the app is writing the break schedule into a protected folder?

**Comment by mcanyucel** [comment] 2021-12-10 12:01
OK I did some digging and it looks like if Controlled Folder Access is enabled under Windows Security>Ransomware Protection, the first break window is shown correctly but the rest is displayed blank. When you disable the controlled folder access, everything works normally. Allowing the Stretchly.exe from the Windows Security Controlled Folder Access settings does not seem to work. Maybe the app is writing schedules to a protected location within a different executable?

**Comment by kevinmcfarlane** [comment] 2021-12-10 14:13
> OK I did some digging and it looks like if Controlled Folder Access is enabled under Windows Security>Ransomware Protection, the first break window is shown correctly but the rest is displayed blank. When you disable the controlled folder access, everything works normally...

Ah, I have Controlled Folder Access enabled too. I'm currently rolled back to 1.7.0. I upgraded to 1.8.1 on my Dad's Win 10 and he had no issues.

**Comment by jnpwly** [comment] 2021-12-11 01:23
Interesting... but this is perhaps only part of the issue, as I do not have "Controlled folder access" enabled, but saw this problem in Stretchly v1.8 and v1.8.1.

![image](https://user-images.githubusercontent.com/10701621/145658841-33d616d9-0a74-4f7b-b503-db5734ff9f78.png)

**Comment by IshanManchanda** [comment] 2021-12-14 04:48
Can confirm @jnpwly's experience, I also have Controlled folder access turned off but am facing the same issue in v1.8 and v1.8.1. 

This also seems to be the same as #1048. @hovancik, anything in this thread that helps you isolate/reproduce? Since most of us are reasonably sure we haven't had this prior to v1.8, it might make sense to look through what changed. Although GH shows 1,101 file changes here (https://github.com/hovancik/stretchly/compare/v1.7.0...v1.8.0) so may not be feasible.

**Comment by mike-crawfurd** [comment] 2021-12-14 07:55
I have the same issue as above and similar like #1048 I have it on my Mac M1 as well as my Mac Mini as well as Windows 10 and Windows 11 (so four platforms), it is not always consistent, but I would suspect it is not related to any security on the platform (Windows 10/11/Mac) but more something in the attached libraries that is breaking it?

**Comment by robpomeroy** [comment] 2021-12-14 12:07
I'm experiencing the same problem on Win10. Controlled Folder security is disabled.

Interestingly, when I launch Stretchly, the following event appears in the System log:

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user [REDACTED] from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

```

The registry suggests {2593F8B9-4EAF-457C-B68A-50F6B8EA6B54} and {15C20B67-12E7-4BB6-92BB-7AFF07997402} are associated to the RuntimeBroker (which checks app permissions).

Could be a red herring.

**Comment by chobo2** [comment] 2021-12-16 23:45
Same here have the same issue in windows 11, sometimes it shows up correctly sometimes not.

**Comment by globalhuman** [comment] 2021-12-20 04:51
I'm seeing the same issue on macOS 12.1 and ubuntu 20.04

**Comment by vvvlc** [comment] 2021-12-21 09:08
I report the same issue with the screen I'm on W10, in my case 1st automated break is ok but from that moment on any automated break is white. When triggering break from menu window looks ok. This start happening after the upgrade from 1.7.0

**Comment by hovancik** [comment] 2021-12-22 08:03
Yeah, this is the same issue as #1048 . I am not able to reproduce on any of my machines, so can't really tell. I think it is related to how in code Stretchly "asks" for break ideas information and not getting them due to some electron event not being fired.

**Comment by hovancik** [comment] 2021-12-22 08:40
Hi all, I will close this in favor of #1048 . Can you please subscribe there and possibly try running the new branch locally to help with debugging? Thanks a bunch! https://github.com/hovancik/stretchly/issues/1048#issuecomment-999389553

**Closed as completed by hovancik** 2021-12-22 08:40 UTC
