### ISSUE TITLE
Full-screen mode doesn't work well with i3wm

### ISSUE THREAD

**Issue by rudolfbyker** [hovancik/stretchly#361] opened 2019-02-12 08:40 UTC
### Prerequisites

- [x] I'm using latest version: v0.19.0 

### Description

Operating system: LinuxMint 19.1 with i3 window manager 4.16.1

### Steps to Reproduce

1. Install LinuxMint
2. Install i3
3. Install stretchly
5. Configure stretchly for fullscreen notifications (since i3 is a tiling manager, windows don't overlap)

**Expected behavior:** Full screen notification.

**Actual behavior:** Semi-full screen abomination. :rofl: 
![screenshot from 2019-02-12 10-39-26](https://user-images.githubusercontent.com/10025342/52622432-857b0880-2eb2-11e9-8381-fed539a1dc81.png)

**Reproduces how often:** Always.

**Comment by hovancik** [comment] 2019-02-12 17:03
Hi, this is a known electron issue with any Linux desktop ;/ 

The issue is reported for quite some time but nothing's happening 

https://github.com/electron/electron/issues/11632
https://github.com/electron/electron/issues/15471

**Comment by hovancik** [comment] 2019-02-12 17:06
I'll close this in favor of #186

**Closed by hovancik** 2019-02-12 17:06 UTC
